CREATE TABLE `Ingredient` (
  `Value` int NOT NULL,
  `Weight` float NOT NULL,
  `Ingredient` varchar(50) NOT NULL,
  `Weakness to Fire` int DEFAULT NULL,
  `Blind` int DEFAULT NULL,
  `Burden` int DEFAULT NULL,
  `Paralyze` int DEFAULT NULL,
  `Poison` int DEFAULT NULL,
  `Frost Damage` int DEFAULT NULL,
  `Damage Health` int DEFAULT NULL,
  `Drain Health` int DEFAULT NULL,
  `Drain Fatigue` int DEFAULT NULL,
  `Drain Magicka` int DEFAULT NULL,
  `Drain Strength` int DEFAULT NULL,
  `Drain Intelligence` int DEFAULT NULL,
  `Drain Willpower` int DEFAULT NULL,
  `Drain Agility` int DEFAULT NULL,
  `Drain Speed` int DEFAULT NULL,
  `Drain Endurance` int DEFAULT NULL,
  `Drain Personality` int DEFAULT NULL,
  `Drain Luck` int DEFAULT NULL,
  `Fortify Health` int DEFAULT NULL,
  `Fortify Fatigue` int DEFAULT NULL,
  `Fortify Magicka` int DEFAULT NULL,
  `Fortify Strength` int DEFAULT NULL,
  `Fortify Intelligence` int DEFAULT NULL,
  `Fortify Willpower` int DEFAULT NULL,
  `Fortify Agility` int DEFAULT NULL,
  `Fortify Speed` int DEFAULT NULL,
  `Fortify Endurance` int DEFAULT NULL,
  `Fortify Personality` int DEFAULT NULL,
  `Fortify Luck` int DEFAULT NULL,
  `Fortify Attack` int DEFAULT NULL,
  `Restore Health` int DEFAULT NULL,
  `Restore Fatigue` int DEFAULT NULL,
  `Restore Magicka` int DEFAULT NULL,
  `Restore Strength` int DEFAULT NULL,
  `Restore Intelligence` int DEFAULT NULL,
  `Restore Willpower` int DEFAULT NULL,
  `Restore Agility` int DEFAULT NULL,
  `Restore Speed` int DEFAULT NULL,
  `Restore Endurance` int DEFAULT NULL,
  `Restore Personality` int DEFAULT NULL,
  `Restore Luck` int DEFAULT NULL,
  `Detect Animal` int DEFAULT NULL,
  `Detect Enchantment` int DEFAULT NULL,
  `Detect Key` int DEFAULT NULL,
  `Dispel` int DEFAULT NULL,
  `Feather` int DEFAULT NULL,
  `Invisibility` int DEFAULT NULL,
  `Levitate` int DEFAULT NULL,
  `Light` int DEFAULT NULL,
  `Night Eye` int DEFAULT NULL,
  `Cure Blight Disease` int DEFAULT NULL,
  `Cure Common Disease` int DEFAULT NULL,
  `Resist Common Disease` int DEFAULT NULL,
  `Cure Paralyzation` int DEFAULT NULL,
  `Resist Paralysis` int DEFAULT NULL,
  `Cure Poison` int DEFAULT NULL,
  `Resist Poison` int DEFAULT NULL,
  `Resist Fire` int DEFAULT NULL,
  `Resist Frost` int DEFAULT NULL,
  `Resist Shock` int DEFAULT NULL,
  `Fire Shield` int DEFAULT NULL,
  `Frost Shield` int DEFAULT NULL,
  `Lightning Shield` int DEFAULT NULL,
  `Resist Magicka` int DEFAULT NULL,
  `Reflect` int DEFAULT NULL,
  `Spell Absorption` int DEFAULT NULL,
  `Telekinesis` int DEFAULT NULL,
  `Swift Swim` int DEFAULT NULL,
  `Water Breathing` int DEFAULT NULL,
  `Water Walking` int DEFAULT NULL,
  PRIMARY KEY (`Ingredient`)
);
CREATE TABLE `Effect` (
  `Spell Effects` varchar(50) NOT NULL,
  `Base Cost` float NOT NULL,
  `Positive` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`Spell Effects`)
);
CREATE TABLE `Tool` (
  `Name` varchar(50) NOT NULL,
  `Quality` float NOT NULL,
  `Type` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Name`)
);