UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Cure Blight Disease";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Cure Common Disease";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Cure Paralyzation";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Cure Poison";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Detect Animal";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Detect Enchantment";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Detect Key";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Dispel"; -- Dispel may remove wanted effects
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Feather";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fire Shield";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Agility";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Attack";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Endurance";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Fatigue";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Health";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Intelligence";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Luck";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Magicka";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Personality";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Speed";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Strength";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Fortify Willpower";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Frost Shield";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Invisibility";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Levitate";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Light";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Lightning Shield";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Night Eye";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Reflect";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Common Disease";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Fire";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Frost";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Magicka";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Paralysis";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Poison";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Resist Shock";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Agility";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Endurance";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Fatigue";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Health";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Intelligence";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Luck";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Magicka";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Personality";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Speed";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Willpower";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore Strength";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Restore ";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Spell Absorption";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Swift Swim";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Telekinesis";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Water Breathing";
UPDATE effect SET Positive = 1 WHERE `Spell Effects`="Water Walking";