INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Blind',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Burden',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Cure Blight Disease',2000,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Cure Common Disease',300,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Cure Paralyzation',100,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Cure Poison',100,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Damage Health',8,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Detect Animal',0.75,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Detect Enchantment',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Detect Key',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Dispel',5,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Agility',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Endurance',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Fatigue',2,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Health',4,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Intelligence',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Luck',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Magicka',4,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Personality',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Speed',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Strength',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Drain Willpower',1,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Feather',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fire Shield',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Agility',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Attack',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Endurance',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Fatigue',0.5,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Health',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Intelligence',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Luck',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Magicka',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Personality',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Speed',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Strength',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Fortify Willpower',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Frost Damage',5,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Frost Shield',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Invisibility',20,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Levitate',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Light',0.2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Lightning Shield',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Night Eye',0.2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Paralyze',40,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Poison',9,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Reflect',10,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Common Disease',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Fire',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Frost',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Magicka',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Paralysis',0.2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Poison',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Resist Shock',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Agility',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Endurance',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Fatigue',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Health',5,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Intelligence',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Luck',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Magicka',5,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Personality',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Speed',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Strength',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Restore Willpower',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Sound',3,NULL);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Spell Absorption',10,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Swift Swim',2,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Telekinesis',1,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Water Breathing',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Water Walking',3,1);
INSERT INTO Effect(`Spell Effects`,`Base Cost`,`Positive`) VALUES ('Weakness to Fire',2,NULL);
