INSERT INTO IngtoNPC(`Name`,`NPCName`,`Count`) VALUES
 ('ingred_vampire_dust_01','Anarenen',-1)
,('ingred_bloat_01','Anarenen',-5)
,('ingred_bonemeal_01','Anarenen',-5)
,('ingred_comberry_01','Anarenen',-10)
,('ingred_crab_meat_01','Anarenen',-10)
,('ingred_diamond_01','Anarenen',-2)
,('ingred_fire_salts_01','Anarenen',-5)
,('ingred_heather_01','Anarenen',-10)
,('ingred_wickwheat_01','Chaplain Ogrul',-10)
,('ingred_saltrice_01','Chaplain Ogrul',-10)
,('ingred_rat_meat_01','Chaplain Ogrul',-10)
,('ingred_marshmerrow_01','Chaplain Ogrul',-10)
,('ingred_crab_meat_01','Chaplain Ogrul',-10)
,('ingred_ash_yam_01','Chaplain Ogrul',-10)
,('food_kwama_egg_01','Ulumpha gra-Sharob',-10)
,('ingred_hound_meat_01','Ulumpha gra-Sharob',-10)
,('ingred_frost_salts_01','Ulumpha gra-Sharob',-5)
,('ingred_bonemeal_01','Ulumpha gra-Sharob',-5)
,('ingred_netch_leather_01','Mehra Drora',-10)
,('ingred_stoneflower_petals_01','Mehra Drora',-10)
,('ingred_fire_petal_01','Mehra Drora',-5)
,('ingred_hackle-lo_leaf_01','Mehra Drora',-5)
,('ingred_ghoul_heart_01','Mehra Drora',-1)
,('ingred_bloat_01','Mehra Drora',-10)
,('ingred_dreugh_wax_01','Mehra Drora',-5)
,('food_kwama_egg_01','Zanmulk Sammalamus',-10)
,('ingred_hound_meat_01','Zanmulk Sammalamus',-10)
,('ingred_rat_meat_01','Zanmulk Sammalamus',-10)
,('ingred_ash_yam_01','Zanmulk Sammalamus',-10)
,('ingred_bittergreen_petals_01','Zanmulk Sammalamus',-10)
,('ingred_ash_yam_01','Ygfa',-5)
,('ingred_bittergreen_petals_01','Ygfa',-5)
,('ingred_chokeweed_01','Ygfa',-5)
,('ingred_guar_hide_01','Ygfa',-4)
,('ingred_marshmerrow_01','Ygfa',-5)
,('ingred_scuttle_01','Guls Llervu',-5)
,('ingred_scathecraw_01','Guls Llervu',-5)
,('ingred_saltrice_01','Guls Llervu',-5)
,('ingred_resin_01','Guls Llervu',-5)
,('ingred_kagouti_hide_01','Guls Llervu',-5)
,('ingred_corkbulb_root_01','Guls Llervu',-5)
,('ingred_willow_anther_01','Ajira',-5)
,('ingred_scales_01','Ajira',-5)
,('food_kwama_egg_01','Ajira',-5)
,('ingred_kwama_cuttle_01','Ajira',-5)
,('ingred_hound_meat_01','Ajira',-5)
,('ingred_heather_01','Ajira',-5)
,('ingred_crab_meat_01','Ajira',-5)
,('ingred_comberry_01','Ajira',-5)
,('ingred_black_anther_01','Ajira',-5)
,('ingred_corprus_weepings_01','Threvul Serethi',-5)
,('ingred_bittergreen_petals_01','Threvul Serethi',-10)
,('ingred_wickwheat_01','Threvul Serethi',-10)
,('ingred_scuttle_01','Threvul Serethi',-5)
,('ingred_scrib_jelly_01','Threvul Serethi',-5)
,('ingred_netch_leather_01','Threvul Serethi',-5)
,('food_kwama_egg_01','Threvul Serethi',-10)
,('ingred_hound_meat_01','Threvul Serethi',-10)
,('ingred_coprinus_01','Anis Seloth',-10)
,('ingred_russula_01','Anis Seloth',-10)
,('ingred_bc_hypha_facia','Anis Seloth',-10)
,('ingred_bc_coda_flower','Anis Seloth',-10)
,('ingred_willow_anther_01','Anis Seloth',-10)
,('ingred_wickwheat_01','Anis Seloth',-10)
,('ingred_vampire_dust_01','Anis Seloth',-2)
,('ingred_trama_root_01','Anis Seloth',-10)
,('ingred_sload_soap_01','Anis Seloth',-10)
,('ingred_scrap_metal_01','Anis Seloth',-5)
,('ingred_scales_01','Anis Seloth',-10)
,('ingred_ruby_01','Anis Seloth',-4)
,('ingred_pearl_01','Anis Seloth',-4)
,('ingred_muck_01','Anis Seloth',-10)
,('ingred_kwama_cuttle_01','Anis Seloth',-10)
,('ingred_hackle-lo_leaf_01','Anis Seloth',-10)
,('ingred_heather_01','Anis Seloth',-10)
,('ingred_ghoul_heart_01','Anis Seloth',-2)
,('ingred_frost_salts_01','Anis Seloth',-5)
,('ingred_fire_salts_01','Anis Seloth',-5)
,('ingred_diamond_01','Anis Seloth',-4)
,('ingred_daedras_heart_01','Anis Seloth',-2)
,('ingred_daedra_skin_01','Anis Seloth',-2)
,('ingred_bonemeal_01','Anis Seloth',-10)
,('ingred_bloat_01','Anis Seloth',-10)
,('ingred_alit_hide_01','Anis Seloth',-5)
,('ingred_fire_petal_01','Pierlette Rostorard',-5)
,('ingred_stoneflower_petals_01','Pierlette Rostorard',-10)
,('ingred_shalk_resin_01','Pierlette Rostorard',-5)
,('ingred_scathecraw_01','Pierlette Rostorard',-10)
,('ingred_roobrush_01','Pierlette Rostorard',-5)
,('ingred_resin_01','Pierlette Rostorard',-10)
,('ingred_red_lichen_01','Pierlette Rostorard',-5)
,('ingred_kresh_fiber_01','Pierlette Rostorard',-10)
,('ingred_kagouti_hide_01','Pierlette Rostorard',-10)
,('ingred_ectoplasm_01','Pierlette Rostorard',-5)
,('ingred_dreugh_wax_01','Pierlette Rostorard',-5)
,('ingred_black_lichen_01','Pierlette Rostorard',-5)
,('ingred_bc_bungler''s_bane','Tusamircil',-5)
,('ingred_bc_ampoule_pod','Tusamircil',-5)
,('ingred_bc_spore_pod','Tusamircil',-5)
,('ingred_trama_root_01','Tusamircil',-10)
,('ingred_racer_plumes_01','Tusamircil',-10)
,('food_kwama_egg_01','Tusamircil',-10)
,('ingred_kwama_cuttle_01','Tusamircil',-10)
,('ingred_hound_meat_01','Tusamircil',-10)
,('ingred_crab_meat_01','Tusamircil',-10)
,('ingred_corkbulb_root_01','Tusamircil',-10)
,('ingred_guar_hide_01','Aunius Autrus',-5)
,('ingred_scamp_skin_01','Aunius Autrus',-5)
,('ingred_ash_yam_01','Aunius Autrus',-10)
,('ingred_bloat_01','Aunius Autrus',-5)
,('ingred_netch_leather_01','Aunius Autrus',-5)
,('ingred_scrib_jerky_01','Aunius Autrus',-10)
,('ingred_gravedust_01','Aunius Autrus',-5)
,('ingred_green_lichen_01','Scelian Plebo',-5)
,('ingred_emerald_01','Scelian Plebo',-2)
,('ingred_corprus_weepings_01','Scelian Plebo',-5)
,('ingred_chokeweed_01','Scelian Plebo',-10)
,('ingred_saltrice_01','Scelian Plebo',-10)
,('ingred_rat_meat_01','Scelian Plebo',-10)
,('ingred_marshmerrow_01','Scelian Plebo',-10)
,('ingred_comberry_01','Scelian Plebo',-10)
,('ingred_bonemeal_01','Scelian Plebo',-5)
,('ingred_bittergreen_petals_01','Scelian Plebo',-10)
,('ingred_ash_salts_01','Scelian Plebo',-5)
,('ingred_fire_petal_01','Cocistian Quaspus',-5)
,('ingred_stoneflower_petals_01','Cocistian Quaspus',-5)
,('ingred_scathecraw_01','Cocistian Quaspus',-10)
,('ingred_rat_meat_01','Cocistian Quaspus',-10)
,('ingred_kresh_fiber_01','Cocistian Quaspus',-10)
,('ingred_emerald_01','Cocistian Quaspus',-2)
,('ingred_bittergreen_petals_01','Cocistian Quaspus',-10)
,('ingred_hound_meat_01','Arnand Liric',-10)
,('ingred_netch_leather_01','Arnand Liric',-5)
,('ingred_scamp_skin_01','Arnand Liric',-5)
,('ingred_corprus_weepings_01','Arnand Liric',-5)
,('ingred_scrib_jelly_01','Arnand Liric',-10)
,('ingred_gravedust_01','Arnand Liric',-10)
,('ingred_ash_yam_01','Dulian',-10)
,('ingred_kwama_cuttle_01','Dulian',-10)
,('ingred_muck_01','Dulian',-5)
,('ingred_resin_01','Dulian',-5)
,('ingred_scrib_jerky_01','Dulian',-10)
,('ingred_willow_anther_01','Dulian',-5)
,('ingred_trama_root_01','Dulian',-5)
,('ingred_black_lichen_01','Somutis Vunnis',-5)
,('ingred_ash_salts_01','Somutis Vunnis',-5)
,('ingred_dreugh_wax_01','Somutis Vunnis',-5)
,('ingred_kresh_fiber_01','Somutis Vunnis',-5)
,('ingred_roobrush_01','Somutis Vunnis',-5)
,('ingred_fire_petal_01','Somutis Vunnis',-5)
,('ingred_bc_spore_pod','Peragon',-5)
,('ingred_bc_coda_flower','Peragon',-5)
,('ingred_russula_01','Peragon',-5)
,('ingred_sload_soap_01','Peragon',-5)
,('ingred_pearl_01','Peragon',-2)
,('ingred_heather_01','Peragon',-5)
,('ingred_gold_kanet_01','Peragon',-5)
,('ingred_vampire_dust_01','Nalcarya of White Haven',-1)
,('ingred_trama_root_01','Nalcarya of White Haven',-10)
,('ingred_sload_soap_01','Nalcarya of White Haven',-10)
,('ingred_scrap_metal_01','Nalcarya of White Haven',-10)
,('ingred_scales_01','Nalcarya of White Haven',-10)
,('ingred_ruby_01','Nalcarya of White Haven',-3)
,('ingred_racer_plumes_01','Nalcarya of White Haven',-10)
,('ingred_pearl_01','Nalcarya of White Haven',-3)
,('ingred_muck_01','Nalcarya of White Haven',-10)
,('ingred_kwama_cuttle_01','Nalcarya of White Haven',-10)
,('ingred_fire_salts_01','Nalcarya of White Haven',-5)
,('ingred_frost_salts_01','Nalcarya of White Haven',-5)
,('ingred_diamond_01','Nalcarya of White Haven',-1)
,('ingred_daedras_heart_01','Nalcarya of White Haven',-1)
,('ingred_daedra_skin_01','Nalcarya of White Haven',-1)
,('ingred_bloat_01','Nalcarya of White Haven',-10)
,('ingred_black_anther_01','Nalcarya of White Haven',-10)
,('ingred_alit_hide_01','Nalcarya of White Haven',-10)
,('ingred_void_salts_01','Nalcarya of White Haven',-7)
,('ingred_ghoul_heart_01','Lloros Sarano',-2)
,('ingred_shalk_resin_01','Lloros Sarano',-5)
,('ingred_red_lichen_01','Lloros Sarano',-5)
,('ingred_gravedust_01','Lloros Sarano',-10)
,('ingred_bread_01','Agning',-5)
,('ingred_trama_root_01','Andilu Drothan',-5)
,('ingred_sload_soap_01','Andilu Drothan',-5)
,('ingred_scrap_metal_01','Andilu Drothan',-4)
,('ingred_heather_01','Andilu Drothan',-5)
,('ingred_gold_kanet_01','Andilu Drothan',-5)
,('ingred_comberry_01','Andilu Drothan',-5)
,('ingred_muck_01','Andilu Drothan',-5)
,('ingred_black_anther_01','Aurane Frernis',-5)
,('ingred_resin_01','Aurane Frernis',-5)
,('ingred_red_lichen_01','Aurane Frernis',-5)
,('ingred_shalk_resin_01','Aurane Frernis',-5)
,('ingred_bc_coda_flower','Aurane Frernis',-5)
,('ingred_bc_hypha_facia','Aurane Frernis',-5)
,('ingred_corprus_weepings_01','Aurane Frernis',-3)
,('ingred_green_lichen_01','Aurane Frernis',-5)
,('ingred_bc_spore_pod','Ernand Thierry',-5)
,('ingred_russula_01','Ernand Thierry',-5)
,('ingred_coprinus_01','Ernand Thierry',-5)
,('ingred_bc_ampoule_pod','Ernand Thierry',-5)
,('ingred_bc_coda_flower','Ernand Thierry',-5)
,('ingred_corkbulb_root_01','Ernand Thierry',-5)
,('ingred_alit_hide_01','Ernand Thierry',-5)
,('ingred_stoneflower_petals_01','Andil',-10)
,('ingred_shalk_resin_01','Andil',-5)
,('ingred_scathecraw_01','Andil',-10)
,('ingred_marshmerrow_01','Andil',-10)
,('ingred_kresh_fiber_01','Andil',-5)
,('ingred_gold_kanet_01','Andil',-10)
,('ingred_black_anther_01','Andil',-10)
,('ingred_ash_salts_01','Relms Gilvilo',-5)
,('ingred_black_lichen_01','Relms Gilvilo',-5)
,('ingred_dreugh_wax_01','Relms Gilvilo',-5)
,('ingred_fire_salts_01','Relms Gilvilo',-5)
,('ingred_ghoul_heart_01','Relms Gilvilo',-1)
,('ingred_roobrush_01','Relms Gilvilo',-5)
,('ingred_scrib_jelly_01','Relms Gilvilo',-5)
,('ingred_vampire_dust_01','Brarayni Sarys',-1)
,('ingred_bc_coda_flower','Brarayni Sarys',-5)
,('ingred_bc_spore_pod','Brarayni Sarys',-5)
,('ingred_sload_soap_01','Brarayni Sarys',-5)
,('ingred_racer_plumes_01','Brarayni Sarys',-10)
,('ingred_muck_01','Brarayni Sarys',-10)
,('ingred_heather_01','Brarayni Sarys',-10)
,('ingred_ghoul_heart_01','Brarayni Sarys',-1)
,('ingred_diamond_01','Brarayni Sarys',-2)
,('ingred_daedra_skin_01','Brarayni Sarys',-2)
,('ingred_black_anther_01','Brarayni Sarys',-10)
,('ingred_scuttle_01','Felara Andrethi',-5)
,('ingred_scamp_skin_01','Felara Andrethi',-5)
,('ingred_saltrice_01','Felara Andrethi',-10)
,('ingred_rat_meat_01','Felara Andrethi',-10)
,('ingred_marshmerrow_01','Felara Andrethi',-10)
,('food_kwama_egg_01','Felara Andrethi',-10)
,('ingred_comberry_01','Felara Andrethi',-10)
,('ingred_chokeweed_01','Felara Andrethi',-4)
,('ingred_wickwheat_01','Irna Maryon',-10)
,('ingred_fire_petal_01','Irna Maryon',-10)
,('ingred_scathecraw_01','Irna Maryon',-10)
,('ingred_roobrush_01','Irna Maryon',-5)
,('ingred_red_lichen_01','Irna Maryon',-3)
,('ingred_kwama_cuttle_01','Irna Maryon',-5)
,('ingred_green_lichen_01','Irna Maryon',-3)
,('ingred_emerald_01','Irna Maryon',-2)
,('ingred_black_lichen_01','Irna Maryon',-3)
,('ingred_stoneflower_petals_01','Bildren Areleth',-10)
,('ingred_resin_01','Bildren Areleth',-5)
,('ingred_kresh_fiber_01','Bildren Areleth',-10)
,('ingred_kagouti_hide_01','Bildren Areleth',-5)
,('ingred_heather_01','Bildren Areleth',-10)
,('ingred_ectoplasm_01','Bildren Areleth',-5)
,('ingred_bittergreen_petals_01','Bildren Areleth',-10)
,('ingred_willow_anther_01','Gils Drelas',-10)
,('ingred_void_salts_01','Gils Drelas',-2)
,('ingred_trama_root_01','Gils Drelas',-5)
,('ingred_scrap_metal_01','Gils Drelas',-5)
,('ingred_scales_01','Gils Drelas',-10)
,('ingred_ruby_01','Gils Drelas',-3)
,('ingred_pearl_01','Gils Drelas',-3)
,('ingred_hackle-lo_leaf_01','Gils Drelas',-10)
,('ingred_gold_kanet_01','Gils Drelas',-10)
,('ingred_frost_salts_01','Gils Drelas',-4)
,('ingred_fire_salts_01','Gils Drelas',-4)
,('ingred_daedras_heart_01','Gils Drelas',-2)
,('ingred_coprinus_01','Jolda',-10)
,('ingred_russula_01','Jolda',-10)
,('ingred_bc_bungler''s_bane','Jolda',-5)
,('ingred_bc_hypha_facia','Jolda',-5)
,('ingred_bc_ampoule_pod','Jolda',-5)
,('ingred_void_salts_01','Jolda',-5)
,('ingred_resin_01','Jolda',-10)
,('ingred_pearl_01','Jolda',-2)
,('ingred_dreugh_wax_01','Jolda',-5)
,('ingred_black_lichen_01','Jolda',-5)
,('ingred_ash_salts_01','Tivam Sadri',-5)
,('ingred_corkbulb_root_01','Tivam Sadri',-5)
,('ingred_ectoplasm_01','Tivam Sadri',-10)
,('ingred_ghoul_heart_01','Tivam Sadri',-1)
,('ingred_gravedust_01','Tivam Sadri',-10)
,('ingred_hackle-lo_leaf_01','Tivam Sadri',-10)
,('ingred_muck_01','Tivam Sadri',-10)
,('ingred_saltrice_01','Tivam Sadri',-10)
,('ingred_scrib_jerky_01','Tivam Sadri',-10)
,('ingred_bloat_01','Daynali Dren',-10)
,('ingred_alit_hide_01','Daynali Dren',-5)
,('ingred_hound_meat_01','Daynali Dren',-10)
,('ingred_willow_anther_01','Daynali Dren',-10)
,('ingred_trama_root_01','Daynali Dren',-10)
,('ingred_scrap_metal_01','Daynali Dren',-5)
,('ingred_scales_01','Daynali Dren',-10)
,('ingred_ruby_01','Daynali Dren',-4)
,('ingred_racer_plumes_01','Daynali Dren',-10)
,('ingred_hackle-lo_leaf_01','Daynali Dren',-10)
,('ingred_gold_kanet_01','Daynali Dren',-10)
,('ingred_frost_salts_01','Daynali Dren',-5)
,('ingred_diamond_01','Daynali Dren',-3)
,('ingred_crab_meat_01','Daynali Dren',-10)
,('ingred_black_anther_01','Daynali Dren',-10)
,('ingred_scrib_jerky_01','Eldrilu Dalen',-5)
,('ingred_scrib_jelly_01','Eldrilu Dalen',-5)
,('ingred_saltrice_01','Eldrilu Dalen',-10)
,('ingred_netch_leather_01','Eldrilu Dalen',-10)
,('ingred_guar_hide_01','Eldrilu Dalen',-10)
,('ingred_fire_salts_01','Eldrilu Dalen',-5)
,('ingred_corkbulb_root_01','Eldrilu Dalen',-10)
,('ingred_ash_yam_01','Eldrilu Dalen',-5)
,('ingred_ash_salts_01','Eldrilu Dalen',-5)
,('ingred_ectoplasm_01','Galuro Belan',-3)
,('ingred_kresh_fiber_01','Galuro Belan',-5)
,('ingred_kagouti_hide_01','Galuro Belan',-5)
,('ingred_scathecraw_01','Galuro Belan',-5)
,('ingred_stoneflower_petals_01','Galuro Belan',-5)
,('ingred_fire_petal_01','Galuro Belan',-5)
,('ingred_wickwheat_01','Milar Maryon',-10)
,('ingred_rat_meat_01','Milar Maryon',-10)
,('ingred_marshmerrow_01','Milar Maryon',-10)
,('ingred_gravedust_01','Milar Maryon',-10)
,('ingred_crab_meat_01','Milar Maryon',-10)
,('ingred_comberry_01','Milar Maryon',-10)
,('ingred_bonemeal_01','Milar Maryon',-5)
,('ingred_ash_yam_01','Milar Maryon',-5)
,('ingred_bc_ampoule_pod','Craetia Jullalian',-5)
,('ingred_fire_salts_01','Craetia Jullalian',-5)
,('ingred_frost_salts_01','Craetia Jullalian',-5)
,('ingred_bloat_01','Craetia Jullalian',-5)
,('ingred_daedras_heart_01','Craetia Jullalian',-1)
,('ingred_diamond_01','Craetia Jullalian',-2)
,('ingred_ruby_01','Craetia Jullalian',-2)
,('ingred_crab_meat_01','Craetia Jullalian',-5)
,('ingred_alit_hide_01','Craetia Jullalian',-5)
,('ingred_corkbulb_root_01','Craetia Jullalian',-5)
,('ingred_emerald_01','Craetia Jullalian',-2)
,('ingred_pearl_01','Craetia Jullalian',-2)
,('ingred_racer_plumes_01','Craetia Jullalian',-5)
,('ingred_ghoul_heart_01','Craetia Jullalian',-1)
,('ingred_ash_yam_01','J''Rasha',-5)
,('ingred_chokeweed_01','J''Rasha',-5)
,('food_kwama_egg_01','J''Rasha',-5)
,('ingred_marshmerrow_01','J''Rasha',-5)
,('ingred_scamp_skin_01','J''Rasha',-3)
,('ingred_saltrice_01','J''Rasha',-5)
,('ingred_scuttle_01','J''Rasha',-5)
,('ingred_dreugh_wax_01','Salen Ravel',-5)
,('ingred_ectoplasm_01','Salen Ravel',-5)
,('ingred_gravedust_01','Salen Ravel',-10)
,('ingred_kagouti_hide_01','Salen Ravel',-10)
,('ingred_shalk_resin_01','Salen Ravel',-5)
,('ingred_saltrice_01','Sedris Omalen',-10)
,('ingred_alit_hide_01','Sedris Omalen',-10)
,('ingred_black_lichen_01','Sedris Omalen',-3)
,('ingred_corkbulb_root_01','Sedris Omalen',-10)
,('ingred_hackle-lo_leaf_01','Sedris Omalen',-5)
,('ingred_corkbulb_root_01','Ganalyn Saram',-5)
,('ingred_hound_meat_01','Ganalyn Saram',-5)
,('ingred_kwama_cuttle_01','Ganalyn Saram',-5)
,('ingred_scales_01','Ganalyn Saram',-5)
,('ingred_willow_anther_01','Ganalyn Saram',-5)
,('ingred_bc_bungler''s_bane','Ganalyn Saram',-5)
,('ingred_bc_spore_pod','Ganalyn Saram',-5)
,('ingred_void_salts_01','Garas Seloth',-2)
,('ingred_pearl_01','Garas Seloth',-2)
,('ingred_wickwheat_01','Garas Seloth',-5)
,('ingred_bonemeal_01','Garas Seloth',-5)
,('ingred_daedra_skin_01','Garas Seloth',-2)
,('ingred_hackle-lo_leaf_01','Garas Seloth',-5)
,('ingred_racer_plumes_01','Garas Seloth',-5)
,('ingred_rat_meat_01','Vaval Selas',-5)
,('ingred_saltrice_01','Vaval Selas',-5)
,('ingred_scrib_jerky_01','Vaval Selas',-5)
,('ingred_gravedust_01','Vaval Selas',-5)
,('ingred_bittergreen_petals_01','Vaval Selas',-5)
,('ingred_chokeweed_01','Vaval Selas',-5)
,('food_kwama_egg_01','Vaval Selas',-5)
,('ingred_willow_anther_01','Llathyno Hlaalu',-5)
,('ingred_trama_root_01','Llathyno Hlaalu',-5)
,('ingred_stoneflower_petals_01','Llathyno Hlaalu',-5)
,('ingred_scuttle_01','Llathyno Hlaalu',-5)
,('ingred_scrib_jelly_01','Llathyno Hlaalu',-5)
,('ingred_resin_01','Llathyno Hlaalu',-5)
,('ingred_muck_01','Llathyno Hlaalu',-5)
,('ingred_kresh_fiber_01','Llathyno Hlaalu',-5)
,('ingred_gravedust_01','Llathyno Hlaalu',-5)
,('ingred_wickwheat_01','Llarara Omayn',-5)
,('ingred_shalk_resin_01','Llarara Omayn',-5)
,('ingred_scrib_jerky_01','Llarara Omayn',-5)
,('ingred_saltrice_01','Llarara Omayn',-5)
,('ingred_hackle-lo_leaf_01','Llarara Omayn',-5)
,('ingred_ectoplasm_01','Llarara Omayn',-5)
,('ingred_corkbulb_root_01','Llarara Omayn',-5)
,('ingred_rat_meat_01','Telis Salvani',-5)
,('ingred_netch_leather_01','Telis Salvani',-5)
,('ingred_green_lichen_01','Telis Salvani',-5)
,('ingred_comberry_01','Telis Salvani',-5)
,('ingred_chokeweed_01','Telis Salvani',-5)
,('ingred_bittergreen_petals_01','Telis Salvani',-5)
,('ingred_ash_salts_01','Telis Salvani',-5)
,('ingred_bc_hypha_facia','Dralval Andrano',-5)
,('ingred_bc_bungler''s_bane','Dralval Andrano',-5)
,('ingred_wickwheat_01','Dralval Andrano',-5)
,('ingred_scathecraw_01','Dralval Andrano',-5)
,('ingred_red_lichen_01','Dralval Andrano',-5)
,('ingred_marshmerrow_01','Dralval Andrano',-5)
,('ingred_kagouti_hide_01','Dralval Andrano',-5)
,('ingred_green_lichen_01','Dralval Andrano',-5)
,('ingred_black_lichen_01','Dralval Andrano',-5)
,('ingred_scuttle_01','Folvys Andalor',-10)
,('ingred_scrib_jerky_01','Folvys Andalor',-10)
,('ingred_scrib_jelly_01','Folvys Andalor',-10)
,('ingred_scamp_skin_01','Folvys Andalor',-10)
,('ingred_rat_meat_01','Folvys Andalor',-10)
,('ingred_guar_hide_01','Folvys Andalor',-10)
,('ingred_emerald_01','Folvys Andalor',-3)
,('ingred_corprus_weepings_01','Folvys Andalor',-5)
,('ingred_ash_salts_01','Folvys Andalor',-5)
,('ingred_bc_bungler''s_bane','Danoso Andrano',-10)
,('ingred_bc_hypha_facia','Danoso Andrano',-10)
,('ingred_bc_coda_flower','Danoso Andrano',-10)
,('ingred_bc_spore_pod','Danoso Andrano',-10)
,('ingred_wickwheat_01','Danoso Andrano',-10)
,('ingred_roobrush_01','Danoso Andrano',-10)
,('ingred_pearl_01','Danoso Andrano',-3)
,('ingred_marshmerrow_01','Danoso Andrano',-10)
,('ingred_ectoplasm_01','Danoso Andrano',-5)
,('ingred_dreugh_wax_01','Danoso Andrano',-5)
,('ingred_scrib_jerky_01','Arrille',-5)
,('ingred_shalk_resin_01','Arrille',-5)
,('ingred_corkbulb_root_01','Arrille',-5)
,('ingred_bread_01','Alcedonia Amnis',-10)
,('ingred_crab_meat_01','Alcedonia Amnis',-3)
,('ingred_hound_meat_01','Alcedonia Amnis',-3)
,('Ingred_horn_lily_bulb_01','Galsa Andrano',-5)
,('Ingred_nirthfly_stalks_01','Galsa Andrano',-5)
,('Ingred_sweetpulp_01','Galsa Andrano',-5)
,('ingred_scrib_jerky_01','Galsa Andrano',-5)
,('ingred_netch_leather_01','Mehra Helas',-10)
,('ingred_stoneflower_petals_01','Mehra Helas',-10)
,('ingred_fire_petal_01','Mehra Helas',-5)
,('ingred_hackle-lo_leaf_01','Mehra Helas',-5)
,('ingred_ghoul_heart_01','Mehra Helas',-1)
,('ingred_bloat_01','Mehra Helas',-10)
,('ingred_dreugh_wax_01','Mehra Helas',-5)
,('ingred_ash_yam_01','Ra''Tesh',-5)
,('ingred_bread_01','Ra''Tesh',-5)
,('ingred_crab_meat_01','Ra''Tesh',-5)
,('ingred_hound_meat_01','Ra''Tesh',-5)
,('ingred_scrib_jerky_01','Ra''Tesh',-5)
,('ingred_wickwheat_01','Ra''Tesh',-5)
,('ingred_saltrice_01','Ra''Tesh',-5)
,('T_IngFood_MeatDolphin_01','Alona',3)
,('T_IngFood_Apple_01','Appinora Essorinus',-4)
,('T_IngFood_BreadColovian_01','Appinora Essorinus',-3)
,('T_IngFood_BreadColovian_02','Appinora Essorinus',-3)
,('T_IngFood_CheeseColovian_01','Appinora Essorinus',-3)
,('T_IngFood_Cookie_01','Appinora Essorinus',-3)
,('T_IngFood_Fig_Dried_01','Appinora Essorinus',-2)
,('T_IngFood_Lyco_01','Appinora Essorinus',-2)
,('T_IngFlor_CairnBolete_01','Breathes-Deep',-3)
,('T_IngFlor_LadysMantle_01','Breathes-Deep',-2)
,('T_IngFlor_Persarine_01','Caltierra Sivus',3)
,('T_IngCrea_GoldTanthaBeak_01','Ceryl',-5)
,('T_IngCrea_Muskratfur_01','Ceryl',-5)
,('T_IngFlor_AloeVeraPulp_01','Ceryl',-5)
,('T_IngFlor_Ginseng_01','Ceryl',-5)
,('T_IngFlor_Thungleweed_01','Ceryl',-5)
,('T_IngFood_Rice_01','Ceryl',-5)
,('ingred_crab_meat_01','Ceryl',-5)
,('T_IngFood_Blueberry_01','Christophe Marane',2)
,('T_IngFood_CheeseRedguard_01','Christophe Marane',1)
,('T_IngFood_TartRedguard_01','Christophe Marane',1)
,('T_IngCrea_SturgeonMeat_01','Concera Dantian',2)
,('food_kwama_egg_02','Corethyn Surano',10)
,('T_IngCrea_SturgeonMeat_01','Edan Juros',2)
,('T_IngMine_Salt_01','Gorri',1)
,('ingred_moon_sugar_01','Imulav Fulcius',-3)
,('ingred_rat_meat_01','Imulav Fulcius',-3)
,('T_IngFood_BreadColovian_01','Ireldaya',-5)
,('T_IngFood_BreadColovian_02','Ireldaya',-1)
,('T_IngFood_MeatArenthJerky_01','Julius Volchar',-2)
,('ingred_bread_01','Julius Volchar',-3)
,('T_IngCrea_OysterMeat_02','Kathrelor',5)
,('T_IngFlor_Cabbage_01','Lennox',-1)
,('T_IngFood_PastryFrRedguard_01','Lennox',3)
,('T_IngFood_TartRedguard_01','Lennox',1)
,('T_IngMine_Salt_01','Lihien Mandilaron',2)
,('T_IngFood_BreadColovian_02','Lugroth gro-Burshok',-3)
,('T_IngFood_CheeseColovian_01','Lugroth gro-Burshok',-3)
,('T_IngFlor_Nightshade_01','Melia Simerius',-4)
,('T_IngCrea_TanthaEgg_01','Miles Catraso',1)
,('T_IngFood_MeatArenthJerky_01','Miles Catraso',1)
,('T_IngCrea_DuskyParrotfish_01','Paulia Surettian',2)
,('T_IngFood_MeatDolphin_01','Paulia Surettian',1)
,('T_IngCrea_SturgeonMeat_01','Paulia Surettian',3)
,('T_IngCrea_SturgeonRoe_01','Paulia Surettian',1)
,('T_IngCrea_Angelfish_01','Pessius Vrocha',3)
,('T_IngCrea_SeaUrchinMeat_01','Pessius Vrocha',5)
,('T_IngCrea _StridentBirdEgg_01','Philus Verius',3)
,('T_IngCrea _StridentBirdFeath_01','Philus Verius',1)
,('T_IngFood_Rice_01','Philus Verius',3)
,('T_IngFood_BreadColovian_01','Reyan',-3)
,('T_IngFood_BreadColovian_02','Reyan',-2)
,('ingred_bread_01','Reyan',-4)
,('T_IngFood_Leek_01','Ulgith',1)
,('T_IngFood_MeatSqrl_01','Ulgith',1)
,('T_IngFood_Mango_01','Varotia Clovas',1)
,('T_IngFood_Blueberry_01','Varotia Clovas',1)
,('T_IngFood_PassionFruit_01','Varotia Clovas',2)
,('T_IngFlor_LadysMantle_01','Weara Galdan',1)
,('T_IngCrea _StridentBirdFeath_01','Lentivus Orien',4)
,('T_IngCrea_AebisFeathers_01','Lentivus Orien',1)
,('T_IngCrea_GoatPelt_01','Lentivus Orien',1)
,('T_IngCrea_GoldTanthaBeak_01','Lentivus Orien',4)
,('T_IngCrea_TanthaEgg_01','Lentivus Orien',2)
,('T_IngFood_MeatHorse_01','Lentivus Orien',5)
,('ingred_bear_pelt','Lentivus Orien',2)
,('ingred_wolf_pelt','Lentivus Orien',3)
,('T_IngCrea_BearpeltBlack_01','Imraic',-1)
,('T_IngCrea_WormmouthHide_01','Imraic',-2)
,('T_IngFood_MeatBoar_02','Imraic',-2)
,('T_IngFood_MeatHorse_01','Imraic',-1)
,('T_IngFood_AppleSkyrim_01','Berwa',-2)
,('T_IngFood_BreadColovian_01','Berwa',-3)
,('T_IngFood_BreadFlat_03','Berwa',-3)
,('T_IngFood_CheeseNord_01','Berwa',-3)
,('T_IngFood_MeatBoar_02','Berwa',-2)
,('T_IngFood_MeatChicken_01','Berwa',-3)
,('T_IngCrea_KoboldTongue_01','Jhorcian',-2)
,('T_IngCrea_SnowraySting_01','Jhorcian',-3)
,('T_IngCrea_SnowraySting_01','Ywain',-1)
,('ingred_moon_sugar_01','Idah',-7)
,('T_IngFood_AppleSkyrim_01','Kem',-3)
,('T_IngFood_BreadColovian_01','Kem',-2)
,('T_IngFood_MeatBeef_01','Kem',-3)
,('T_IngFood_MeatVenison_01','Kem',-2)
,('T_IngFood_Potato_01','Kem',-2)
,('T_IngFood_BreadColovian_01','Lelena Aurtius',-4)
,('T_IngFood_BreadColovian_02','Lelena Aurtius',-5)
,('T_IngFood_BreadFlat_01','Lelena Aurtius',-3)
,('T_IngFood_Cookie_01','Lelena Aurtius',-3)
,('T_IngFood_EggChicken_01','Lelena Aurtius',-3)
,('T_IngFood_Flour_01','Lelena Aurtius',-6)
,('T_IngFood_Honey_01','Lelena Aurtius',-2)
,('T_IngFood_Sweetroll_01','Lelena Aurtius',-2)
,('T_IngFood_Wheat_01','Lelena Aurtius',-5)
,('ingred_bread_01','Lelena Aurtius',-3)
,('T_IngFlor_Dragynia_01','Hoota',3)
,('T_IngFlor_ForsythiaTrRoots_01','Hoota',1)
,('T_IngFlor_HoneyLily_01','Hoota',2)
,('T_IngFood_Honey_01','Hoota',1)
,('T_IngFood_MeatBeef_01','Hoota',1)
,('T_IngFood_MeatBoar_02','Hoota',1)
,('T_IngFood_Onion_01','Hoota',3)
,('T_IngFood_Potato_01','Hoota',1)
,('T_IngFood_Radish_01','Hoota',1)
,('T_IngFlor_HoneyLily_01','Razhab',2)
,('T_IngFlor_HoneyLily_02','Razhab',3)
,('T_IngFlor_Nightshade_01','Razhab',3)
,('T_IngFlor_Redpoppy_01','Razhab',1)
,('T_IngFood_AppleSkyrim_01','Ildgar Fire-Tongue',-8)
,('T_IngFood_BreadColovian_01','Ildgar Fire-Tongue',-6)
,('T_IngFood_CheeseNord_01','Ildgar Fire-Tongue',-5)
,('T_IngFood_FishPike_01','Ildgar Fire-Tongue',-2)
,('T_IngFood_FishSalmon_01','Ildgar Fire-Tongue',-2)
,('T_IngFood_MeatBoar_02','Ildgar Fire-Tongue',-3)
,('T_IngFood_MeatChicken_01','Ildgar Fire-Tongue',-4)
,('ingred_moon_sugar_01','J''zarr',-3)
,('T_IngFlor_Taragetis_01','Rulat gra-Khagim',2)
,('T_IngFlor_TrembleWeedSap_01','Rulat gra-Khagim',2)
,('T_IngFlor_Trollroot_01','Rulat gra-Khagim',1)
,('ingred_emerald_01','Rianard Bauvrise',1)
,('T_IngFood_BreadFlat_01','Lorvacah',-3)
,('T_IngFood_CheeseNord_01','Lorvacah',-2)
,('T_IngFood_Garlic_01','Lorvacah',-1)
,('T_IngFood_MeatChicken_01','Lorvacah',-2)
,('T_IngFood_Onion_01','Lorvacah',-2)
,('ingred_bonemeal_01','Naureen',-1)
,('ingred_scuttle_01','Naureen',5)
,('ingred_scales_01','Slick-Skewer',-3)
,('ingred_scrib_jerky_01','Slick-Skewer',-2)
,('ingred_comberry_01','Andoren Beleth',-3)
,('ingred_wickwheat_01','Andoren Beleth',10)
,('ingred_bread_01','Athenim Adri',1)
,('ingred_muck_01','Elammu Andrani',-3)
,('ingred_scales_01','Elammu Andrani',-5)
,('ingred_ruby_01','Ferala Aranith',1)
,('T_IngFood_EggMolecrab_01','Hlarvys Duren',-2)
,('T_IngFood_FishSlaughterDried_01','Hlarvys Duren',-4)
,('T_IngCrea_FlyMusk_01','Irele Nathryon',-2)
,('T_IngFlor_Nightshade_01','Irele Nathryon',-4)
,('T_IngFood_EggOrnada_01','Irele Nathryon',-3)
,('T_IngFood_MeatAlit_01','Irele Nathryon',-3)
,('T_IngFood_MeatCliffracer_01','Irele Nathryon',-3)
,('T_IngFood_MeatGuar_01','Irele Nathryon',-3)
,('T_IngFood_MeatKagouti_01','Irele Nathryon',-3)
,('T_IngFood_MeatKwama_01','Irele Nathryon',-3)
,('T_IngFood_MeatOrnada_01','Irele Nathryon',-3)
,('food_kwama_egg_01','Irele Nathryon',-6)
,('food_kwama_egg_02','Irele Nathryon',-6)
,('ingred_alit_hide_01','Irele Nathryon',-3)
,('ingred_ash_salts_01','Irele Nathryon',-3)
,('ingred_ash_yam_01','Irele Nathryon',-3)
,('ingred_heather_01','Irele Nathryon',-5)
,('ingred_hound_meat_01','Irele Nathryon',-3)
,('ingred_muck_01','Irele Nathryon',-3)
,('ingred_racer_plumes_01','Irele Nathryon',-3)
,('ingred_rat_meat_01','Irele Nathryon',-3)
,('ingred_resin_01','Irele Nathryon',-4)
,('ingred_russula_01','Irele Nathryon',-5)
,('ingred_saltrice_01','Irele Nathryon',-5)
,('ingred_scales_01','Irele Nathryon',-3)
,('ingred_scamp_skin_01','Irele Nathryon',-3)
,('food_kwama_egg_01','Jana Livia',-5)
,('food_kwama_egg_02','Jana Livia',-5)
,('ingred_saltrice_01','Jana Livia',-4)
,('ingred_sload_soap_01','Jana Livia',-5)
,('T_IngFood_BreadColovian_01','Nilara Beleth',-1)
,('T_IngFood_BreadColovian_02','Nilara Beleth',-3)
,('Ingred_golden_sedge_01','Olanasa Wenil',-1)
,('ingred_chokeweed_01','Olanasa Wenil',-1)
,('ingred_comberry_01','Olanasa Wenil',-1)
,('ingred_saltrice_01','Olanasa Wenil',-1)
,('T_IngFood_BreadColovian_01','Sa''assa',2)
,('T_IngFood_Cookie_02','Sa''assa',1)
,('ingred_hackle-lo_leaf_01','Sa''assa',2)
,('ingred_saltrice_01','Sa''assa',15)
,('ingred_scathecraw_01','Sa''assa',5)
,('ingred_wickwheat_01','Sa''assa',10)
,('T_IngCrea_CephalopodShell_01','Siriele Nathryon',-5)
,('ingred_bc_hypha_facia','Siriele Nathryon',-5)
,('ingred_bonemeal_01','Siriele Nathryon',-10)
,('ingred_hackle-lo_leaf_01','Siriele Nathryon',-10)
,('ingred_muck_01','Siriele Nathryon',-10)
,('ingred_scales_01','Siriele Nathryon',-10)
,('ingred_wickwheat_01','Siriele Nathryon',-10)
,('T_IngCrea_FlyMusk_01','Alenial',-2)
,('T_IngFlor_Bluefoot_01','Alenial',-2)
,('T_IngFood_FishSlaughterDried_02','Alenial',-2)
,('food_kwama_egg_02','Alenial',1)
,('ingred_ash_salts_01','Alenial',-1)
,('ingred_bittergreen_petals_01','Alenial',-1)
,('ingred_corkbulb_root_01','Alenial',-1)
,('ingred_guar_hide_01','Alenial',-1)
,('ingred_kresh_fiber_01','Alenial',-1)
,('ingred_muck_01','Alenial',-1)
,('ingred_red_lichen_01','Alenial',-1)
,('ingred_trama_root_01','Alenial',-1)
,('T_IngFood_BreadColovian_01','Audania Ranius',-6)
,('T_IngFood_BreadColovian_02','Audania Ranius',-6)
,('T_IngFood_MeatAlit_01','Audania Ranius',-3)
,('T_IngFood_MeatGuar_01','Audania Ranius',-3)
,('T_IngFood_MeatKagouti_01','Audania Ranius',-3)
,('T_IngFood_MeatKwama_01','Audania Ranius',-3)
,('T_IngFood_MeatOrnada_01','Audania Ranius',-2)
,('T_IngFood_Sweetroll_01','Audania Ranius',-8)
,('ingred_bread_01','Audania Ranius',-4)
,('ingred_crab_meat_01','Audania Ranius',-4)
,('ingred_hound_meat_01','Audania Ranius',-3)
,('ingred_rat_meat_01','Audania Ranius',-3)
,('ingred_saltrice_01','Audania Ranius',-10)
,('ingred_scuttle_01','Audania Ranius',-3)
,('food_kwama_egg_01','Brinda Vorenis',10)
,('food_kwama_egg_02','Brinda Vorenis',6)
,('ingred_bread_01','Brinda Vorenis',6)
,('ingred_chokeweed_01','Calaciren',-5)
,('ingred_kresh_fiber_01','Calaciren',-5)
,('ingred_marshmerrow_01','Calaciren',-5)
,('ingred_saltrice_01','Calaciren',-5)
,('ingred_stoneflower_petals_01','Calaciren',-5)
,('ingred_daedra_skin_01','Dilavesa Indalen',1)
,('ingred_daedras_heart_01','Dilavesa Indalen',1)
,('ingred_diamond_01','Dilavesa Indalen',1)
,('ingred_dreugh_wax_01','Dilavesa Indalen',1)
,('ingred_ectoplasm_01','Dilavesa Indalen',-2)
,('ingred_emerald_01','Dilavesa Indalen',1)
,('ingred_gravedust_01','Dilavesa Indalen',2)
,('ingred_gravetar_01','Dilavesa Indalen',1)
,('ingred_guar_hide_01','Dilavesa Indalen',-1)
,('ingred_hackle-lo_leaf_01','Dilavesa Indalen',-2)
,('ingred_heather_01','Dilavesa Indalen',-2)
,('ingred_hound_meat_01','Dilavesa Indalen',-3)
,('ingred_pearl_01','Dilavesa Indalen',-1)
,('ingred_raw_ebony_01','Dilavesa Indalen',1)
,('ingred_raw_glass_01','Dilavesa Indalen',1)
,('ingred_raw_glass_tinos','Dilavesa Indalen',1)
,('ingred_saltrice_01','Dilavesa Indalen',-5)
,('ingred_trama_root_01','Dilavesa Indalen',-1)
,('ingred_wickwheat_01','Dilavesa Indalen',-2)
,('ingred_willow_anther_01','Dilavesa Indalen',-3)
,('T_IngFood_BreadColovian_01','Fevras Beran',-2)
,('T_IngFood_BreadColovian_02','Fevras Beran',-2)
,('T_IngFood_MeatGuar_01','Fevras Beran',-2)
,('food_kwama_egg_01','Fevras Beran',-4)
,('food_kwama_egg_02','Fevras Beran',-1)
,('ingred_bread_01','Fevras Beran',-15)
,('ingred_muck_01','Fevras Beran',-3)
,('food_kwama_egg_01','Gadali Sarothril',-8)
,('food_kwama_egg_02','Gadali Sarothril',-6)
,('ingred_bread_01','Gadali Sarothril',-7)
,('food_kwama_egg_01','Garer Llenas',-3)
,('ingred_bread_01','Garer Llenas',-10)
,('ingred_hound_meat_01','Garer Llenas',-2)
,('T_IngCrea_BeetleResin_01','Herea Nerthul',-3)
,('T_IngFood_MeatAlit_01','Herea Nerthul',-3)
,('T_IngFood_MeatCliffracer_01','Herea Nerthul',-3)
,('T_IngFood_MeatGuar_01','Herea Nerthul',-3)
,('T_IngFood_MeatParastylus_01','Herea Nerthul',-1)
,('ingred_alit_hide_01','Herea Nerthul',-3)
,('ingred_bc_hypha_facia','Herea Nerthul',-2)
,('ingred_bc_spore_pod','Herea Nerthul',-2)
,('ingred_bittergreen_petals_01','Herea Nerthul',-2)
,('ingred_bonemeal_01','Herea Nerthul',-5)
,('ingred_chokeweed_01','Herea Nerthul',-3)
,('ingred_comberry_01','Herea Nerthul',-2)
,('ingred_fire_salts_01','Herea Nerthul',-1)
,('ingred_frost_salts_01','Herea Nerthul',-1)
,('ingred_hound_meat_01','Herea Nerthul',-2)
,('ingred_kagouti_hide_01','Herea Nerthul',-2)
,('ingred_kwama_cuttle_01','Herea Nerthul',-3)
,('ingred_muck_01','Herea Nerthul',-5)
,('ingred_rat_meat_01','Herea Nerthul',-3)
,('ingred_saltrice_01','Herea Nerthul',-8)
,('ingred_scuttle_01','Herea Nerthul',-1)
,('ingred_trama_root_01','Herea Nerthul',-2)
,('ingred_wickwheat_01','Herea Nerthul',-8)
,('T_IngCrea_BeetleResin_01','Mamani Benapal',1)
,('T_IngMine_Opal_01','Mamani Benapal',1)
,('ingred_rat_meat_01','Mamani Benapal',2)
,('ingred_saltrice_01','Mamani Benapal',4)
,('ingred_scales_01','Mervyn Andalas',-5)
,('ingred_pearl_01','Pedivur',-4)
,('ingred_scales_01','Pedivur',-10)
,('Ingred_meadow_rye_01','Polodie Floine',-3)
,('T_IngCrea_BeetleShell_01','Polodie Floine',-2)
,('T_IngCrea_BeetleShell_02','Polodie Floine',-2)
,('T_IngCrea_BeetleShell_03','Polodie Floine',-2)
,('T_IngCrea_BeetleShell_04','Polodie Floine',-2)
,('T_IngFood_MeatCliffracer_01','Polodie Floine',-2)
,('ingred_comberry_01','Polodie Floine',-3)
,('ingred_guar_hide_01','Polodie Floine',-3)
,('ingred_netch_leather_01','Polodie Floine',-4)
,('ingred_racer_plumes_01','Polodie Floine',-5)
,('ingred_scuttle_01','Polodie Floine',-4)
,('T_IngFood_EggMolecrab_01','Rithin Helvas',-2)
,('T_IngFood_MeatGuar_01','Rithin Helvas',-2)
,('T_IngFood_MeatKagouti_01','Rithin Helvas',-2)
,('ingred_chokeweed_01','Rithin Helvas',-7)
,('ingred_comberry_01','Rithin Helvas',-5)
,('ingred_crab_meat_01','Rithin Helvas',-4)
,('ingred_fire_petal_01','Rithin Helvas',-3)
,('ingred_guar_hide_01','Rithin Helvas',-4)
,('ingred_hound_meat_01','Rithin Helvas',-4)
,('ingred_marshmerrow_01','Rithin Helvas',-6)
,('ingred_saltrice_01','Rithin Helvas',-9)
,('ingred_scales_01','Rithin Helvas',-5)
,('ingred_scrib_jelly_01','Rithin Helvas',-3)
,('Ingred_meadow_rye_01','Roshaga gra-Horg',-2)
,('T_IngFood_EggMolecrab_01','Roshaga gra-Horg',-3)
,('T_IngFood_EggOrnada_01','Roshaga gra-Horg',-3)
,('food_kwama_egg_01','Roshaga gra-Horg',-5)
,('food_kwama_egg_02','Roshaga gra-Horg',-5)
,('ingred_guar_hide_01','Roshaga gra-Horg',-3)
,('ingred_kwama_cuttle_01','Roshaga gra-Horg',-2)
,('ingred_sload_soap_01','Roshaga gra-Horg',-2)
,('T_IngFood_MeatGuar_01','Sathys Norvayn',-3)
,('ingred_guar_hide_01','Sathys Norvayn',-3)
,('ingred_hound_meat_01','Sathys Norvayn',-3)
,('ingred_saltrice_01','Sathys Norvayn',-10)
,('ingred_wickwheat_01','Sathys Norvayn',-10)
,('food_kwama_egg_02','Tinaso Sadus',2)
,('ingred_bread_01','Tinaso Sadus',5)
,('ingred_comberry_01','Tinaso Sadus',2)
,('ingred_holly_01','Tinaso Sadus',2)
,('ingred_saltrice_01','Tinaso Sadus',5)
,('ingred_wickwheat_01','Tinaso Sadus',5)
,('ingred_chokeweed_01','Tiunia Veltrus',-5)
,('ingred_marshmerrow_01','Tiunia Veltrus',-5)
,('ingred_saltrice_01','Tiunia Veltrus',-5)
,('food_kwama_egg_01','Uleras Morenu',-4)
,('food_kwama_egg_02','Uleras Morenu',-5)
,('ingred_bread_01','Uleras Morenu',-6)
,('T_IngFood_MeatCliffracer_01','Varvsa Romori',-1)
,('T_IngFood_MeatGuar_01','Varvsa Romori',-2)
,('T_IngFood_MeatKagouti_01','Varvsa Romori',-4)
,('T_IngFood_MeatKwama_01','Varvsa Romori',-4)
,('food_kwama_egg_01','Varvsa Romori',-3)
,('food_kwama_egg_02','Varvsa Romori',-5)
,('ingred_bread_01','Varvsa Romori',-10)
,('ingred_guar_hide_01','Varvsa Romori',-1)
,('ingred_racer_plumes_01','Varvsa Romori',-1)
,('T_IngFood_MeatCliffracer_01','Alammu Vandalas',-2)
,('T_IngFood_ScribPie_01','Alammu Vandalas',-2)
,('food_kwama_egg_01','Alammu Vandalas',-3)
,('food_kwama_egg_02','Alammu Vandalas',-2)
,('ingred_corkbulb_root_01','Alammu Vandalas',-2)
,('ingred_crab_meat_01','Alammu Vandalas',-5)
,('ingred_hackle-lo_leaf_01','Alammu Vandalas',-6)
,('ingred_muck_01','Alammu Vandalas',-3)
,('ingred_racer_plumes_01','Alammu Vandalas',-2)
,('ingred_rat_meat_01','Alammu Vandalas',-2)
,('ingred_scales_01','Alammu Vandalas',-3)
,('T_IngCrea_MoonMothWing_01','Amelphia Tarramon',-2)
,('ingred_bc_hypha_facia','Amelphia Tarramon',-3)
,('ingred_frost_salts_01','Amelphia Tarramon',-1)
,('ingred_scrib_jelly_01','Amelphia Tarramon',4)
,('T_IngFood_BreadDeshaan_02','Andilu Ornovl',1)
,('T_IngFood_BreadDeshaan_03','Andilu Ornovl',2)
,('ingred_bc_coda_flower','Andilu Ornovl',1)
,('ingred_saltrice_01','Andilu Ornovl',4)
,('T_IngFlor_WhitePoppyPod_01','Andril Selothi',1)
,('ingred_green_lichen_01','Andril Selothi',3)
,('ingred_heather_01','Andril Selothi',4)
,('ingred_scrib_jelly_01','Andril Selothi',1)
,('ingred_willow_anther_01','Andril Selothi',3)
,('T_IngFood_FishSlaughterDried_01','Ano Dreloth',-2)
,('T_IngFood_FishSlaughterDried_02','Ano Dreloth',-2)
,('T_IngFood_FishSlaughterDried_03','Ano Dreloth',-2)
,('ingred_crab_meat_01','Ano Dreloth',-3)
,('T_IngFlor_HoneyLily_02','Arivanya',3)
,('T_IngFlor_LichenOrange_01','Arivanya',2)
,('T_IngSpice_Hibiscus_01','Arivanya',3)
,('ingred_ash_salts_01','Arivanya',3)
,('ingred_ash_yam_01','Arivanya',-5)
,('ingred_bonemeal_01','Arivanya',5)
,('ingred_chokeweed_01','Arivanya',3)
,('ingred_comberry_01','Arivanya',-3)
,('ingred_corkbulb_root_01','Arivanya',-2)
,('ingred_green_lichen_01','Arivanya',3)
,('ingred_hackle-lo_leaf_01','Arivanya',-5)
,('ingred_heather_01','Arivanya',3)
,('ingred_kresh_fiber_01','Arivanya',3)
,('ingred_rat_meat_01','Arivanya',5)
,('ingred_saltrice_01','Arivanya',-5)
,('ingred_scrib_jelly_01','Arivanya',5)
,('ingred_scuttle_01','Arivanya',-5)
,('ingred_stoneflower_petals_01','Arivanya',-2)
,('ingred_trama_root_01','Arivanya',3)
,('ingred_wickwheat_01','Arivanya',5)
,('Ingred_golden_sedge_01','Bariel',-1)
,('Ingred_nirthfly_stalks_01','Bariel',-3)
,('Ingred_noble_sedge_01','Bariel',-1)
,('Ingred_sweetpulp_01','Bariel',-1)
,('T_IngFlor_BlackrosePetal_01','Bariel',-2)
,('ingred_bc_ampoule_pod','Bariel',-1)
,('ingred_bc_coda_flower','Bariel',-1)
,('ingred_black_anther_01','Bariel',-2)
,('ingred_gold_kanet_01','Bariel',-3)
,('ingred_heather_01','Bariel',-3)
,('ingred_willow_anther_01','Bariel',-2)
,('T_IngFood_EggOrnada_01','Bols Naroth',-5)
,('ingred_rat_meat_01','Bols Naroth',-2)
,('ingred_saltrice_01','Bols Naroth',-5)
,('ingred_scrib_jerky_01','Bols Naroth',-5)
,('ingred_scuttle_01','Bols Naroth',-3)
,('ingred_wickwheat_01','Bols Naroth',-8)
,('T_IngFood_BreadColovian_01','Calsa Attius',-12)
,('T_IngFood_BreadColovian_02','Calsa Attius',-6)
,('T_IngFood_ScribPie_01','Calsa Attius',-3)
,('T_IngFood_Sweetroll_01','Calsa Attius',-12)
,('ingred_bread_01','Calsa Attius',-6)
,('ingred_comberry_01','Calsa Attius',-6)
,('ingred_wickwheat_01','Calsa Attius',-9)
,('T_IngCrea_BeetleResin_01','Celina Russus',-2)
,('T_IngFlor_Lavender_01','Celina Russus',-4)
,('T_IngFlor_Weepveil_01','Celina Russus',-5)
,('T_IngFlor_WhitePoppyPod_01','Celina Russus',-3)
,('T_IngSpice_Drumpear_01','Celina Russus',-3)
,('ingred_ash_salts_01','Celina Russus',-2)
,('ingred_bc_coda_flower','Celina Russus',-5)
,('ingred_daedra_skin_01','Celina Russus',-2)
,('ingred_dreugh_wax_01','Celina Russus',-2)
,('ingred_frost_salts_01','Celina Russus',-2)
,('ingred_hackle-lo_leaf_01','Celina Russus',-4)
,('ingred_racer_plumes_01','Celina Russus',-3)
,('ingred_shalk_resin_01','Celina Russus',-4)
,('ingred_trama_root_01','Celina Russus',-4)
,('ingred_willow_anther_01','Celina Russus',-3)
,('T_IngFood_Bread_03','Charna gra-Mohl',-1)
,('T_IngFood_MeatCliffracer_01','Charna gra-Mohl',-1)
,('T_IngFood_ScribPie_01','Charna gra-Mohl',-2)
,('food_kwama_egg_01','Charna gra-Mohl',-2)
,('food_kwama_egg_02','Charna gra-Mohl',-3)
,('ingred_hound_meat_01','Charna gra-Mohl',-4)
,('ingred_fire_petal_01','Cirtiel',-1)
,('ingred_heather_01','Cirtiel',-1)
,('food_kwama_egg_01','Darane Navur',-3)
,('ingred_guar_hide_01','Darane Navur',-2)
,('T_IngFood_FishSlaughterDried_01','Dilvene Gilmanil',-5)
,('ingred_bread_01','Dilvene Gilmanil',2)
,('ingred_crab_meat_01','Dilvene Gilmanil',-2)
,('ingred_scales_01','Dilvene Gilmanil',-2)
,('T_IngFood_Bread_01','Dinara Nelan',-3)
,('T_IngFood_Bread_02','Dinara Nelan',-10)
,('T_IngFood_Bread_03','Dinara Nelan',-2)
,('T_IngFood_Cookie_01','Dinara Nelan',-3)
,('T_IngFood_Cookie_02','Dinara Nelan',-3)
,('T_IngFood_ScribPie_01','Dinara Nelan',-2)
,('ingred_bread_01','Dinara Nelan',-3)
,('T_IngFood_MeatGuar_01','Dolyn Volor',-6)
,('T_IngFood_MeatKwama_01','Dolyn Volor',-3)
,('ingred_hound_meat_01','Dolyn Volor',-5)
,('ingred_rat_meat_01','Dolyn Volor',-5)
,('T_IngCrea_YethResin_01','Doves Silvin',-1)
,('T_IngFlor_Weepveil_01','Doves Silvin',-2)
,('ingred_ash_salts_01','Doves Silvin',-2)
,('ingred_hackle-lo_leaf_01','Doves Silvin',-3)
,('ingred_sload_soap_01','Doves Silvin',-2)
,('T_IngFood_MeatBoar_02','Dralin Belvayn',1)
,('T_IngFood_MeatKagouti_01','Dralin Belvayn',-4)
,('T_IngFood_MeatKwama_01','Dralin Belvayn',-4)
,('T_IngFood_MeatMutton_01','Dralin Belvayn',-5)
,('T_IngFood_ScribPie_01','Dralin Belvayn',-1)
,('T_IngFood_Sweetroll_01','Dralin Belvayn',-5)
,('ingred_bread_01','Dralin Belvayn',-6)
,('ingred_comberry_01','Dralin Belvayn',-2)
,('ingred_hound_meat_01','Dralin Belvayn',-4)
,('T_IngCrea_Eyestar_01','Draraynea Nelas',2)
,('T_IngFlor_OrangeMoss_01','Draraynea Nelas',1)
,('T_IngFood_FishSlaughterDried_01','Draraynea Nelas',-2)
,('ingred_scales_01','Draraynea Nelas',-4)
,('Ingred_meadow_rye_01','Drimsu Gindol',-2)
,('Ingred_noble_sedge_01','Drimsu Gindol',-2)
,('Ingred_sweetpulp_01','Drimsu Gindol',-2)
,('Ingred_timsa-come-by_01','Drimsu Gindol',-23)
,('T_IngCrea_BeetleResin_01','Drimsu Gindol',-5)
,('T_IngCrea_BeetleShell_01','Drimsu Gindol',-1)
,('T_IngCrea_BeetleShell_02','Drimsu Gindol',-1)
,('T_IngCrea_BeetleShell_03','Drimsu Gindol',-1)
,('T_IngCrea_BeetleShell_04','Drimsu Gindol',-1)
,('T_IngCrea_ShellParastylus_01','Drimsu Gindol',-5)
,('T_IngFlor_AloeVeraPulp_01','Drimsu Gindol',-2)
,('T_IngFlor_Bluefoot_01','Drimsu Gindol',-1)
,('T_IngFlor_Nightshade_01','Drimsu Gindol',-5)
,('T_IngFood_EggMolecrab_01','Drimsu Gindol',-5)
,('T_IngFood_FishSlaughterDried_01','Drimsu Gindol',-5)
,('T_IngFood_MeatAlit_01','Drimsu Gindol',-5)
,('T_IngFood_MeatGuar_01','Drimsu Gindol',-5)
,('T_IngFood_MeatKagouti_01','Drimsu Gindol',-5)
,('T_IngFood_MeatKwama_01','Drimsu Gindol',-5)
,('T_IngFood_MeatParastylus_01','Drimsu Gindol',-5)
,('ingred_alit_hide_01','Drimsu Gindol',-5)
,('ingred_ash_yam_01','Drimsu Gindol',-5)
,('ingred_bc_ampoule_pod','Drimsu Gindol',-5)
,('ingred_bc_bungler''s_bane','Drimsu Gindol',-5)
,('ingred_bc_coda_flower','Drimsu Gindol',-5)
,('ingred_bc_hypha_facia','Drimsu Gindol',-5)
,('ingred_bc_spore_pod','Drimsu Gindol',-5)
,('ingred_black_anther_01','Drimsu Gindol',-5)
,('ingred_black_lichen_01','Drimsu Gindol',-5)
,('ingred_bonemeal_01','Drimsu Gindol',-5)
,('ingred_bread_01','Drimsu Gindol',-5)
,('ingred_chokeweed_01','Drimsu Gindol',-5)
,('ingred_comberry_01','Drimsu Gindol',-5)
,('ingred_corkbulb_root_01','Drimsu Gindol',-5)
,('ingred_crab_meat_01','Drimsu Gindol',-5)
,('ingred_dreugh_wax_01','Drimsu Gindol',-5)
,('ingred_ectoplasm_01','Drimsu Gindol',-5)
,('ingred_fire_petal_01','Drimsu Gindol',-3)
,('ingred_frost_salts_01','Drimsu Gindol',-5)
,('ingred_gold_kanet_01','Drimsu Gindol',-2)
,('ingred_gravedust_01','Drimsu Gindol',-5)
,('ingred_green_lichen_01','Drimsu Gindol',-2)
,('ingred_guar_hide_01','Drimsu Gindol',-5)
,('ingred_hackle-lo_leaf_01','Drimsu Gindol',-5)
,('ingred_heather_01','Drimsu Gindol',-5)
,('ingred_hound_meat_01','Drimsu Gindol',-5)
,('ingred_kresh_fiber_01','Drimsu Gindol',-5)
,('ingred_marshmerrow_01','Drimsu Gindol',-5)
,('ingred_muck_01','Drimsu Gindol',-5)
,('ingred_racer_plumes_01','Drimsu Gindol',-5)
,('ingred_rat_meat_01','Drimsu Gindol',-5)
,('ingred_resin_01','Drimsu Gindol',-5)
,('ingred_russula_01','Drimsu Gindol',-5)
,('ingred_saltrice_01','Drimsu Gindol',-5)
,('ingred_scales_01','Drimsu Gindol',-5)
,('ingred_scathecraw_01','Drimsu Gindol',-3)
,('ingred_scrib_jelly_01','Drimsu Gindol',-5)
,('ingred_scrib_jerky_01','Drimsu Gindol',-5)
,('ingred_scuttle_01','Drimsu Gindol',-5)
,('ingred_shalk_resin_01','Drimsu Gindol',-5)
,('ingred_sload_soap_01','Drimsu Gindol',-5)
,('ingred_stoneflower_petals_01','Drimsu Gindol',-5)
,('ingred_trama_root_01','Drimsu Gindol',-2)
,('ingred_wickwheat_01','Drimsu Gindol',-2)
,('ingred_willow_anther_01','Drimsu Gindol',-4)
,('T_IngFlor_Tanna_01','Elynu Varan',-10)
,('T_IngFlor_ThirrineLily_01','Elynu Varan',-10)
,('T_IngMine_PearlBlack_01','Elynu Varan',3)
,('ingred_comberry_01','Elynu Varan',-10)
,('ingred_dreugh_wax_01','Elynu Varan',-5)
,('ingred_hackle-lo_leaf_01','Elynu Varan',-10)
,('ingred_muck_01','Elynu Varan',-5)
,('ingred_pearl_01','Elynu Varan',-3)
,('ingred_saltrice_01','Elynu Varan',-10)
,('ingred_scrib_jerky_01','Elynu Varan',-5)
,('ingred_willow_anther_01','Elynu Varan',-10)
,('T_IngFood_BreadColovian_01','Emaroc Harquart',-6)
,('T_IngFood_BreadColovian_02','Emaroc Harquart',-12)
,('T_IngFood_Sweetroll_01','Emaroc Harquart',-13)
,('ingred_bread_01','Emaroc Harquart',-6)
,('ingred_comberry_01','Emaroc Harquart',-6)
,('ingred_wickwheat_01','Emaroc Harquart',-9);
INSERT INTO IngtoNPC(`Name`,`NPCName`,`Count`) VALUES
 ('Ingred_sweetpulp_01','Emercius Ludoviil',-3)
,('T_IngMine_Sapphire_01','Emercius Ludoviil',-1)
,('T_IngMine_Topaz_01','Emercius Ludoviil',-1)
,('ingred_emerald_01','Emercius Ludoviil',1)
,('ingred_pearl_01','Emercius Ludoviil',-2)
,('ingred_sload_soap_01','Emercius Ludoviil',-1)
,('Ingred_horn_lily_bulb_01','Falas Othril',-6)
,('T_IngFlor_Fireflower_01','Falas Othril',-3)
,('ingred_comberry_01','Falas Othril',-5)
,('ingred_corkbulb_root_01','Falas Othril',-2)
,('ingred_gold_kanet_01','Falas Othril',-4)
,('ingred_heather_01','Falas Othril',-5)
,('ingred_willow_anther_01','Falas Othril',-3)
,('T_IngCrea_BeetleResin_01','Faralval',1)
,('T_IngCrea_Eyestar_01','Faralval',1)
,('T_IngFlor_AloeVeraPulp_01','Faralval',4)
,('T_IngFlor_Nightshade_01','Faralval',1)
,('T_IngFood_MeatAlit_01','Faralval',1)
,('T_IngMine_TopazBlue_01','Faralval',1)
,('ingred_alit_hide_01','Faralval',1)
,('ingred_black_anther_01','Faralval',1)
,('ingred_black_lichen_01','Faralval',1)
,('ingred_fire_petal_01','Faralval',1)
,('ingred_fire_salts_01','Faralval',4)
,('ingred_gravedust_01','Faralval',1)
,('ingred_green_lichen_01','Faralval',1)
,('ingred_heather_01','Faralval',1)
,('ingred_kresh_fiber_01','Faralval',3)
,('ingred_red_lichen_01','Faralval',1)
,('ingred_resin_01','Faralval',6)
,('Ingred_golden_sedge_01','Galran Darvu',-3)
,('Ingred_timsa-come-by_01','Galran Darvu',-5)
,('T_IngFlor_BlueKanet_01','Galran Darvu',-3)
,('ingred_comberry_01','Galran Darvu',-5)
,('ingred_red_lichen_01','Galran Darvu',5)
,('Ingred_meadow_rye_01','Golveso Darys',-5)
,('ingred_chokeweed_01','Golveso Darys',-8)
,('ingred_comberry_01','Golveso Darys',-13)
,('ingred_fire_petal_01','Golveso Darys',-1)
,('ingred_gold_kanet_01','Golveso Darys',-7)
,('ingred_hackle-lo_leaf_01','Golveso Darys',-11)
,('ingred_marshmerrow_01','Golveso Darys',-3)
,('ingred_saltrice_01','Golveso Darys',-12)
,('ingred_wickwheat_01','Golveso Darys',-10)
,('ingred_willow_anther_01','Golveso Darys',-2)
,('ingred_bread_01','Golyn Volor',-6)
,('ingred_bread_01','Gul-Ei',-7)
,('T_IngCrea_VelkNectarSack_01','Ienasa Llothil',4)
,('ingred_moon_sugar_01','J''Raham',-5)
,('ingred_corkbulb_root_01','Jalyin',-2)
,('ingred_marshmerrow_01','Jalyin',3)
,('T_IngFood_MeatMutton_01','Jodald',-3)
,('ingred_bread_01','Jodald',-3)
,('ingred_crab_meat_01','Jodald',-6)
,('Ingred_lloramor_spines_01','Kassad',-1)
,('Ingred_nirthfly_stalks_01','Kassad',-1)
,('Ingred_timsa-come-by_01','Kassad',-2)
,('T_IngFlor_BlackrosePetal_01','Kassad',-2)
,('T_IngFlor_Bluefoot_01','Kassad',-3)
,('T_IngFlor_Hamumroot_01','Kassad',-6)
,('T_IngFlor_OrangeMoss_01','Kassad',-3)
,('ingred_bc_coda_flower','Kassad',-1)
,('ingred_bittergreen_petals_01','Kassad',-10)
,('ingred_black_anther_01','Kassad',-2)
,('ingred_chokeweed_01','Kassad',-4)
,('ingred_corkbulb_root_01','Kassad',-2)
,('ingred_gold_kanet_01','Kassad',-8)
,('ingred_green_lichen_01','Kassad',-1)
,('ingred_hackle-lo_leaf_01','Kassad',-2)
,('ingred_heather_01','Kassad',-5)
,('ingred_red_lichen_01','Kassad',-4)
,('ingred_roobrush_01','Kassad',-3)
,('ingred_saltrice_01','Kassad',-4)
,('ingred_stoneflower_petals_01','Kassad',-2)
,('ingred_willow_anther_01','Kassad',-2)
,('ingred_ash_yam_01','Kiseen',-6)
,('T_IngFlor_BlueKanet_01','Lloryno Norom',-5)
,('food_kwama_egg_01','Lloryno Norom',-5)
,('ingred_bread_01','Lloryno Norom',-3)
,('ingred_comberry_01','Lloryno Norom',-10)
,('ingred_dreugh_wax_01','Lloryno Norom',-3)
,('ingred_scrib_jelly_01','Lloryno Norom',-5)
,('food_kwama_egg_01','Macilda Belladon',1)
,('T_IngFood_MeatGuar_01','Mahhjat',-5)
,('food_kwama_egg_01','Mahhjat',-4)
,('food_kwama_egg_02','Mahhjat',-4)
,('ingred_rat_meat_01','Mahhjat',-3)
,('Ingred_golden_sedge_01','Manus',-6)
,('Ingred_horn_lily_bulb_01','Manus',-12)
,('T_IngCrea_VelkNectarSack_01','Manus',-2)
,('T_IngFood_MeatCliffracer_01','Manus',-1)
,('ingred_corkbulb_root_01','Manus',-4)
,('ingred_marshmerrow_01','Manus',-2)
,('ingred_netch_leather_01','Manus',-4)
,('ingred_racer_plumes_01','Manus',-2)
,('ingred_saltrice_01','Manus',-10)
,('ingred_wickwheat_01','Manus',-7)
,('ingred_willow_anther_01','Manus',-3)
,('T_IngFood_EggOrnada_01','Marayn Voldal',-3)
,('food_kwama_egg_02','Marayn Voldal',-3)
,('ingred_saltrice_01','Marayn Voldal',-6)
,('ingred_scrib_jerky_01','Marayn Voldal',-3)
,('food_kwama_egg_01','Methalas Eves',-3)
,('food_kwama_egg_02','Methalas Eves',-2)
,('ingred_saltrice_01','Methalas Eves',-5)
,('T_IngCrea_FlyMusk_01','Midali Renim',-1)
,('T_IngFood_EggOrnada_01','Midali Renim',-4)
,('T_IngFood_MeatGuar_01','Midali Renim',-1)
,('T_IngFood_MeatKwama_01','Midali Renim',-3)
,('T_IngFood_ScribPie_01','Midali Renim',-2)
,('ingred_alit_hide_01','Midali Renim',-3)
,('ingred_corkbulb_root_01','Midali Renim',-3)
,('ingred_crab_meat_01','Midali Renim',-4)
,('ingred_gold_kanet_01','Midali Renim',-2)
,('ingred_hound_meat_01','Midali Renim',-3)
,('ingred_marshmerrow_01','Midali Renim',5)
,('ingred_black_lichen_01','Mudera Berelan',1)
,('T_IngCrea_MoonMothWing_01','Narusya',-1)
,('T_IngFlor_Nightshade_01','Narusya',-1)
,('T_IngMine_Garnet_01','Narusya',1)
,('ingred_ectoplasm_01','Narusya',-2)
,('ingred_fire_salts_01','Narusya',-5)
,('ingred_frost_salts_01','Narusya',-5)
,('ingred_red_lichen_01','Narusya',-2)
,('Ingred_horn_lily_bulb_01','Orelle Faugard',1)
,('T_IngCrea_MoonMothWing_01','Orelle Faugard',-3)
,('T_IngFlor_OrangeMoss_01','Orelle Faugard',-2)
,('T_IngFlor_TempleDome_01','Orelle Faugard',-1)
,('T_IngMine_Amethyst_01','Orelle Faugard',1)
,('ingred_bc_coda_flower','Orelle Faugard',2)
,('ingred_comberry_01','Orelle Faugard',1)
,('ingred_dreugh_wax_01','Orelle Faugard',-1)
,('ingred_fire_petal_01','Orelle Faugard',1)
,('ingred_fire_salts_01','Orelle Faugard',1)
,('ingred_gravedust_01','Orelle Faugard',1)
,('ingred_green_lichen_01','Orelle Faugard',1)
,('ingred_pearl_01','Rilver Thelas',-2)
,('T_IngFood_FishSlaughterDried_01','Rothis Thalur',-5)
,('ingred_marshmerrow_01','Rothis Thalur',5)
,('T_IngFood_FishSlaughterDried_02','Sallus Pepander',-4)
,('ingred_crab_meat_01','Sallus Pepander',-2)
,('ingred_scales_01','Sallus Pepander',-5)
,('T_IngCrea_VelkNectarSack_01','Thelin Drinith',5)
,('ingred_crab_meat_01','Thelin Drinith',2)
,('ingred_hound_meat_01','Thelin Drinith',2)
,('ingred_kwama_cuttle_01','Thelin Drinith',3)
,('ingred_rat_meat_01','Thelin Drinith',1)
,('ingred_bread_01','Turunstrid Harrow-Hand',-6)
,('T_IngFlor_OrangeMoss_01','Ulvu Ouradas',-4)
,('T_IngFlor_TempleDome_01','Ulvu Ouradas',-3)
,('ingred_fire_petal_01','Ulvu Ouradas',-2)
,('Ingred_noble_sedge_01','Unaarie',-2)
,('T_IngCrea_MoonMothWing_01','Unaarie',-3)
,('T_IngFlor_Bluefoot_01','Unaarie',-5)
,('T_IngMine_OreIron_01','Unaarie',-1)
,('ingred_bc_hypha_facia','Unaarie',-5)
,('ingred_bc_spore_pod','Unaarie',-1)
,('ingred_black_lichen_01','Unaarie',-2)
,('ingred_gold_kanet_01','Unaarie',-3)
,('ingred_gravedust_01','Unaarie',-3)
,('ingred_racer_plumes_01','Unaarie',-2)
,('ingred_scales_01','Unaarie',-4)
,('ingred_scamp_skin_01','Unaarie',-1)
,('ingred_sload_soap_01','Unaarie',-3)
,('ingred_willow_anther_01','Unaarie',-3)
,('T_IngFood_BreadColovian_02','Valia Vautere',-3)
,('T_IngFood_FishSlaughterDried_02','Valia Vautere',-1)
,('T_IngFood_MeatGuar_01','Valia Vautere',-2)
,('T_IngFlor_Bluefoot_01','Sabinus Vanceo',-3)
,('T_IngFlor_TempleDome_01','Sabinus Vanceo',-3)
,('ingred_comberry_01','Vono Sarando',-10)
,('ingred_dreugh_wax_01','Vono Sarando',-5)
,('ingred_gold_kanet_01','Vono Sarando',-5)
,('ingred_willow_anther_01','Vono Sarando',-5)
,('Ingred_scrib_cabbage_01','Yammu Hainnadon',-2)
,('food_kwama_egg_01','Yammu Hainnadon',-2)
,('food_kwama_egg_02','Yammu Hainnadon',-2)
,('ingred_saltrice_01','Yammu Hainnadon',-3)
,('ingred_scrib_jelly_01','Yammu Hainnadon',-2)
,('ingred_scuttle_01','Yammu Hainnadon',-2)
,('T_IngMine_OreGold_01','Anjzhirra',-2)
,('T_IngMine_TopazBlue_01','Anjzhirra',-1)
,('ingred_diamond_01','Anjzhirra',-1)
,('ingred_ruby_01','Anjzhirra',-2)
,('T_IngCrea_AtavisticEye_01','Alam Relvani',-1)
,('T_IngFood_FishSlaughterDried_01','Alam Relvani',-10)
,('T_IngFood_FishSlaughterDried_02','Alam Relvani',-5)
,('ingred_crab_meat_01','Alam Relvani',-7)
,('ingred_scales_01','Alam Relvani',-10)
,('T_IngFlor_BlackrosePetal_01','Cherleynne Vianette',1)
,('T_IngFlor_ThirrineLily_01','Cherleynne Vianette',1)
,('T_IngFood_EggOrnada_01','Cherleynne Vianette',2)
,('T_IngFood_MeatAlit_01','Cherleynne Vianette',1)
,('T_IngMine_Salt_01','Cherleynne Vianette',-3)
,('ingred_pearl_01','Cherleynne Vianette',1)
,('ingred_ash_yam_01','Cirifae',-5)
,('ingred_corkbulb_root_01','Cirifae',-5)
,('T_IngCrea_ArmunHide_01','Dayis Thaar',-5)
,('T_IngCrea_BeetleResin_01','Dayis Thaar',-1)
,('T_IngCrea_Mummyheart_01','Dayis Thaar',-1)
,('ingred_alit_hide_01','Dayis Thaar',1)
,('ingred_bonemeal_01','Dayis Thaar',1)
,('ingred_guar_hide_01','Dayis Thaar',-4)
,('ingred_racer_plumes_01','Dayis Thaar',-3)
,('ingred_scamp_skin_01','Dayis Thaar',-1)
,('ingred_bittergreen_petals_01','Drorayni Omayn',-3)
,('ingred_comberry_01','Drorayni Omayn',1)
,('T_IngCrea_BeetleResin_01','Dulcitius Cullian',1)
,('T_IngCrea_SturgeonRoe_01','Dulcitius Cullian',2)
,('T_IngCrea_YethResin_01','Dulcitius Cullian',-3)
,('T_IngCrea_ArmunHide_01','Garas Orenim',-1)
,('T_IngCrea_BezoarStone_01','Garas Orenim',1)
,('T_IngCrea_CaveTrollEar_01','Garas Orenim',1)
,('T_IngFlor_Nightshade_01','Garas Orenim',-2)
,('T_IngFlor_ThirrineLily_01','Garas Orenim',-2)
,('T_IngFood_EggMolecrab_01','Garas Orenim',-2)
,('T_IngMine_CaputMortuum_01','Garas Orenim',-5)
,('T_IngMine_OreTin_01','Garas Orenim',-2)
,('T_IngMine_Realgar_01','Garas Orenim',-4)
,('ingred_ash_salts_01','Garas Orenim',-3)
,('ingred_comberry_01','Garas Orenim',-3)
,('ingred_daedra_skin_01','Garas Orenim',1)
,('ingred_daedras_heart_01','Garas Orenim',1)
,('ingred_fire_salts_01','Garas Orenim',-3)
,('ingred_frost_salts_01','Garas Orenim',-4)
,('ingred_heather_01','Garas Orenim',-3)
,('ingred_resin_01','Garas Orenim',-5)
,('T_IngFood_MeatAlit_01','Gavros Falas',-2)
,('T_IngFood_MeatOrnada_01','Gavros Falas',-2)
,('ingred_saltrice_01','Gavros Falas',-2)
,('T_IngCrea_ArmunHide_01','Gulvu Dreth',-4)
,('T_IngCrea_Mummyheart_01','Gulvu Dreth',-1)
,('ingred_shalk_resin_01','Gulvu Dreth',-3)
,('T_IngCrea_AtavisticEye_01','Hemmette Fauler',-1)
,('T_IngFlor_Nightshade_01','Hemmette Fauler',-5)
,('T_IngMine_Arsenic_01','Hemmette Fauler',-3)
,('ingred_bc_spore_pod','Hemmette Fauler',-1)
,('ingred_coprinus_01','Hemmette Fauler',-1)
,('ingred_ectoplasm_01','Hemmette Fauler',-1)
,('ingred_green_lichen_01','Hemmette Fauler',-2)
,('ingred_muck_01','Hemmette Fauler',-2)
,('ingred_scales_01','Hemmette Fauler',-3)
,('T_IngFood_MeatGuar_01','Kraki the Grey',-2)
,('ingred_bread_01','Kraki the Grey',-3)
,('ingred_comberry_01','Lechlaud Rorielle',-10)
,('T_IngFood_MeatGuar_01','Nalvos Omayn',3)
,('T_IngFood_MeatKwama_01','Nalvos Omayn',-3)
,('food_kwama_egg_01','Nalvos Omayn',-4)
,('food_kwama_egg_02','Nalvos Omayn',-2)
,('ingred_bread_01','Nalvos Omayn',-4)
,('ingred_comberry_01','Nalvos Omayn',4)
,('ingred_crab_meat_01','Nalvos Omayn',-2)
,('ingred_scrib_jerky_01','Nalvos Omayn',-3)
,('T_IngFood_MeatGuar_01','Narusea Verenim',1)
,('food_kwama_egg_01','Narusea Verenim',1)
,('ingred_bread_01','Narusea Verenim',-4)
,('ingred_kwama_cuttle_01','Narusea Verenim',1)
,('ingred_rat_meat_01','Narusea Verenim',-2)
,('ingred_scrib_jerky_01','Narusea Verenim',-3)
,('T_IngCrea_Eyestar_01','Nevusa Falen',-2)
,('T_IngCrea_Mummyheart_01','Nevusa Falen',-4)
,('T_IngFlor_ThirrineLily_01','Nevusa Falen',-5)
,('T_IngMine_CaputMortuum_01','Nevusa Falen',-3)
,('T_IngMine_OreZinc_01','Nevusa Falen',-1)
,('ingred_comberry_01','Nevusa Falen',-3)
,('ingred_fire_petal_01','Nevusa Falen',-2)
,('ingred_fire_salts_01','Nevusa Falen',-1)
,('ingred_frost_salts_01','Nevusa Falen',-2)
,('ingred_heather_01','Nevusa Falen',-3)
,('ingred_pearl_01','Nevusa Falen',-1)
,('ingred_resin_01','Nevusa Falen',-5)
,('T_IngFood_Flour_01','Nibbles',10)
,('ingred_bread_01','Nibbles',-1)
,('ingred_bread_01','Nivis Dalomo',-2)
,('T_IngFood_MeatGuar_01','Olvys Omayn',1)
,('food_kwama_egg_01','Olvys Omayn',1)
,('ingred_bread_01','Olvys Omayn',-4)
,('ingred_kwama_cuttle_01','Olvys Omayn',1)
,('ingred_rat_meat_01','Olvys Omayn',-2)
,('ingred_scrib_jerky_01','Olvys Omayn',-3)
,('ingred_ash_yam_01','Rolis Hlor',-3)
,('ingred_bread_01','Rolis Hlor',-3)
,('ingred_saltrice_01','Rolis Hlor',-6)
,('Ingred_timsa-come-by_01','Sevilo Serynith',-2)
,('T_IngMine_Arsenic_01','Sevilo Serynith',-2)
,('ingred_fire_petal_01','Sevilo Serynith',-3)
,('ingred_gold_kanet_01','Sevilo Serynith',-3)
,('ingred_stoneflower_petals_01','Sevilo Serynith',-2)
,('T_IngFood_MeatGuar_01','Shalaasa Samane',-3)
,('ingred_black_anther_01','Trehaddi',2)
,('ingred_fire_petal_01','Trehaddi',3)
,('ingred_frost_salts_01','Trehaddi',1)
,('ingred_scamp_skin_01','Trehaddi',1)
,('ingred_scathecraw_01','Trehaddi',3)
,('ingred_trama_root_01','Trehaddi',2)
,('ingred_void_salts_01','Trehaddi',1)
,('ingred_hound_meat_01','Esar-Dan',2)
,('ingred_human_meat_01','Esar-Dan',-4)
,('ingred_kwama_cuttle_01','Esar-Dan',3)
,('ingred_scrib_jelly_01','Esar-Dan',5)
,('T_IngCrea_ArmunHide_01','Yakasamshi Mashda',-1)
,('T_IngCrea_BeetleResin_01','Yakasamshi Mashda',-2)
,('T_IngCrea_BeetleShell_01','Yakasamshi Mashda',-1)
,('T_IngCrea_Mummyheart_01','Yakasamshi Mashda',-1)
,('T_IngFood_MeatGuar_01','Yakasamshi Mashda',-2)
,('ingred_ash_yam_01','Yakasamshi Mashda',-3)
,('ingred_bread_01','Yakasamshi Mashda',-5)
,('ingred_guar_hide_01','Yakasamshi Mashda',-2)
,('ingred_racer_plumes_01','Yakasamshi Mashda',-1)
,('ingred_saltrice_01','Yakasamshi Mashda',-8)
,('ingred_scathecraw_01','Yakasamshi Mashda',-5)
,('T_IngCrea_Eyestar_01','Apphia Calanius',-4)
,('T_IngFlor_AloeVeraPulp_01','Apphia Calanius',-4)
,('T_IngFlor_BlackrosePetal_01','Apphia Calanius',-2)
,('T_IngFlor_SheggoShelf_01','Apphia Calanius',-1)
,('T_IngMine_CaputMortuum_01','Apphia Calanius',-3)
,('T_IngMine_LunarCaustic_01','Apphia Calanius',-1)
,('T_IngMine_OreLead_01','Apphia Calanius',-1)
,('ingred_bloat_01','Apphia Calanius',-3)
,('ingred_chokeweed_01','Apphia Calanius',-2)
,('ingred_dreugh_wax_01','Apphia Calanius',-3)
,('ingred_fire_petal_01','Apphia Calanius',-2)
,('ingred_green_lichen_01','Apphia Calanius',-2)
,('ingred_heather_01','Apphia Calanius',-2)
,('ingred_pearl_01','Apphia Calanius',-3)
,('ingred_scales_01','Apphia Calanius',-2)
,('T_IngFlor_Hamumroot_01','Adas Sarys',-5)
,('T_IngFood_MeatGuar_01','Adas Sarys',-5)
,('ingred_ash_yam_01','Adas Sarys',-10)
,('ingred_guar_hide_01','Adas Sarys',-5)
,('ingred_hackle-lo_leaf_01','Adas Sarys',-5)
,('T_IngFood_MeatAlit_01','Adavas Faryon',-5)
,('ingred_ash_yam_01','Adavas Faryon',-5)
,('ingred_scrib_jerky_01','Adavas Faryon',-5)
,('T_IngCrea_KwoomEgg_01','Ainat Vesuri',1)
,('T_IngCrea_SkyrenderVenom_01','Ainat Vesuri',1)
,('T_IngFlor_DrumpearSeeds_01','Ainat Vesuri',-5)
,('T_IngFlor_Tanna_01','Ainat Vesuri',-7)
,('ingred_corkbulb_root_01','Ainat Vesuri',-7)
,('T_IngFood_MeatGuar_01','Alynu Andrani',4)
,('ingred_guar_hide_01','Alynu Andrani',2)
,('T_IngFood_FishSlaughterDried_01','Anel Rathri',5)
,('ingred_ash_yam_01','Anel Rathri',2)
,('ingred_bread_01','Anel Rathri',10)
,('ingred_crab_meat_01','Anel Rathri',5)
,('ingred_rat_meat_01','Anel Rathri',8)
,('ingred_saltrice_01','Anel Rathri',4)
,('T_IngMine_Amethyst_01','Annalina Conrel',2)
,('T_IngMine_FireOpal_01','Annalina Conrel',1)
,('T_IngMine_Opal_01','Annalina Conrel',1)
,('T_IngMine_OreSilver_01','Annalina Conrel',-2)
,('T_IngMine_Sapphire_01','Annalina Conrel',-1)
,('T_IngFlor_DrumpearSeeds_01','Armas',-5)
,('T_IngFlor_SujPod_01','Armas',-5)
,('food_kwama_egg_01','Armas',-5)
,('ingred_saltrice_01','Armas',-5)
,('ingred_scuttle_01','Armas',-5)
,('T_IngCrea_BeetleResin_01','Arvela Saren',-5)
,('T_IngCrea_BeetleShell_01','Arvela Saren',-6)
,('T_IngCrea_BeetleShell_02','Arvela Saren',-3)
,('T_IngCrea_BeetleShell_04','Arvela Saren',-3)
,('ingred_netch_leather_01','Arvela Saren',-7)
,('T_IngFlor_Tanna_01','Baley',-5)
,('T_IngSpice_Drumpear_01','Baley',-4)
,('ingred_marshmerrow_01','Baley',-3)
,('ingred_saltrice_01','Baley',-5)
,('ingred_wickwheat_01','Baley',-5)
,('T_IngCrea_AtavisticEye_01','Balvo Nothryon',2)
,('T_IngCrea_SkyrenderVenom_01','Balvo Nothryon',4)
,('T_IngFlor_Nightshade_01','Balvo Nothryon',1)
,('T_IngMine_Bloodstone_01','Balvo Nothryon',1)
,('T_IngMine_Opal_01','Balvo Nothryon',3)
,('ingred_moon_sugar_01','Ondres Bethryon',-1)
,('ingred_raw_ebony_01','Ilvel Varyoni',-2)
,('T_IngCrea_MeatHoney_01','Torosi Mavandil',-4)
,('T_IngCrea_OrcBlood_01','Torosi Mavandil',-1)
,('T_IngCrea_TwilightMembrane_01','Torosi Mavandil',-2)
,('T_IngFood_MeatDolphin_01','Torosi Mavandil',-1)
,('T_IngFood_MeatHorse_01','Torosi Mavandil',-1)
,('ingred_6th_corprusmeat_07','Torosi Mavandil',1)
,('ingred_corprus_weepings_01','Torosi Mavandil',-2)
,('ingred_daedra_skin_01','Torosi Mavandil',-1)
,('ingred_moon_sugar_01','Torosi Mavandil',1)
,('ingred_scamp_skin_01','Torosi Mavandil',-3)
,('T_IngFood_Pomegranate_01','Beldar Jerel',-5)
,('ingred_marshmerrow_01','Belvin Uvalas',-3)
,('ingred_bread_01','Beyren Darothril',-3)
,('ingred_scrib_jerky_01','Beyren Darothril',-5)
,('T_IngCrea_HopperAntler_01','Breyis Hallam',-4)
,('T_IngCrea_KwoomFronds','Breyis Hallam',-2)
,('T_IngFlor_Tanna_01','Breyis Hallam',-4)
,('T_IngSpice_Drumpear_01','Breyis Hallam',-2)
,('T_IngCrea_Trollfat_01','Dartis Seran',3)
,('T_IngCrea_YethResin_01','Dartis Seran',1)
,('T_IngFlor_AloeVeraPulp_01','Dartis Seran',1)
,('T_IngFlor_OrangeMoss_01','Dartis Seran',-5)
,('T_IngFlor_TempleDome_01','Dartis Seran',2)
,('T_IngFood_EggMolecrab_01','Dartis Seran',4)
,('T_IngMine_Opal_01','Dartis Seran',1)
,('T_IngMine_Topaz_01','Dartis Seran',1)
,('ingred_ash_yam_01','Dartis Seran',2)
,('ingred_black_lichen_01','Dartis Seran',2)
,('ingred_bloat_01','Dartis Seran',12)
,('ingred_fire_salts_01','Dartis Seran',1)
,('ingred_frost_salts_01','Dartis Seran',1)
,('ingred_gravedust_01','Dartis Seran',5)
,('ingred_green_lichen_01','Dartis Seran',3)
,('ingred_kagouti_hide_01','Dartis Seran',2)
,('ingred_marshmerrow_01','Dartis Seran',-5)
,('ingred_resin_01','Dartis Seran',14)
,('ingred_scrib_jelly_01','Dartis Seran',5)
,('ingred_wickwheat_01','Dartis Seran',4)
,('Ingred_scrib_cabbage_01','Dils Sadri',-5)
,('T_IngFood_FishSlaughterDried_01','Dils Sadri',-5)
,('food_kwama_egg_01','Dils Sadri',-5)
,('food_kwama_egg_02','Dils Sadri',-5)
,('ingred_ash_yam_01','Dils Sadri',-5)
,('ingred_bread_01','Dils Sadri',-5)
,('ingred_crab_meat_01','Dils Sadri',-5)
,('ingred_saltrice_01','Dils Sadri',-5)
,('ingred_scrib_jelly_01','Dils Sadri',-5)
,('T_IngFlor_OrangeMoss_01','Dithisi Andral',3)
,('ingred_ash_yam_01','Dithisi Andral',3)
,('T_IngCrea_Eyestar_01','Do''Zhisi',1)
,('T_IngMine_Jade_01','Do''Zhisi',1)
,('T_IngMine_Opal_01','Do''Zhisi',1)
,('T_IngMine_TopazBlue_01','Do''Zhisi',1)
,('ingred_pearl_01','Do''Zhisi',2)
,('ingred_scrib_jerky_01','Dolmyn Sadri',-3)
,('ingred_ectoplasm_01','Domican Vitresius',1)
,('ingred_gravedust_01','Domican Vitresius',1)
,('ingred_sload_soap_01','Domican Vitresius',1)
,('T_IngFood_Bread_01','Draleru Nerandas',-2)
,('T_IngFood_Bread_02','Draleru Nerandas',-1)
,('ingred_bread_01','Draleru Nerandas',-3)
,('ingred_rat_meat_01','Dramis Vendal',1)
,('T_IngFood_EggOrnada_01','Draren Oril',4)
,('T_IngFood_MeatOrnada_01','Draren Oril',5)
,('ingred_scales_01','Draren Oril',3)
,('T_IngMine_Amethyst_01','Dravosa Avilo',-2)
,('T_IngMine_OrePlatinum_01','Dravosa Avilo',-2)
,('T_IngMine_OreSilver_01','Dravosa Avilo',-2)
,('T_IngMine_Sapphire_01','Dravosa Avilo',-3)
,('food_kwama_egg_02','Drelis Githrano',-3)
,('ingred_scrib_jelly_01','Drelis Githrano',-2)
,('ingred_scrib_jerky_01','Drelis Githrano',-2)
,('T_IngFlor_DrumpearSeeds_01','Edotisu',3)
,('T_IngFlor_Tanna_01','Erilen Rothalor',-3)
,('T_IngFood_EggMolecrab_01','Erilen Rothalor',-3)
,('T_IngFood_EggOrnada_01','Erilen Rothalor',-3)
,('T_IngFood_ScribPie_01','Erilen Rothalor',-2)
,('food_kwama_egg_01','Erilen Rothalor',-3)
,('ingred_ash_yam_01','Erilen Rothalor',-3)
,('ingred_bread_01','Erilen Rothalor',-3)
,('ingred_saltrice_01','Erilen Rothalor',-3)
,('ingred_scrib_jelly_01','Erilen Rothalor',-3)
,('ingred_scrib_jerky_01','Erilen Rothalor',-3)
,('ingred_wickwheat_01','Erilen Rothalor',-3)
,('ingred_ash_yam_01','Evesa Baryon',10)
,('ingred_hackle-lo_leaf_01','Evesa Baryon',10)
,('T_IngFood_FishSlaughterDried_01','Faniriah',5)
,('T_IngFood_MeatOrnada_01','Faniriah',4)
,('T_IngSpice_Drumpear_01','Faniriah',2)
,('food_kwama_egg_01','Faniriah',5)
,('food_kwama_egg_02','Faniriah',2)
,('T_IngCrea_ArmunHide_01','Fanuse Belor',8)
,('T_IngCrea_BeetleShell_01','Fanuse Belor',5)
,('T_IngFood_MeatGuar_01','Fanuse Belor',20)
,('T_IngFood_MeatKagouti_01','Fanuse Belor',20)
,('ingred_guar_hide_01','Fanuse Belor',15)
,('ingred_racer_plumes_01','Fanuse Belor',5)
,('T_IngFlor_Hamumroot_01','Folms Baryon',-5)
,('ingred_corkbulb_root_01','Folms Baryon',-10)
,('T_IngFood_FishSlaughterDried_01','Folms Terians',6)
,('T_IngFood_MeatGuar_01','Folms Terians',5)
,('ingred_scrib_jelly_01','Folms Terians',3)
,('ingred_scuttle_01','Folms Terians',5)
,('T_IngCrea_SkyrenderVenom_01','Gabezu',-5)
,('T_IngCrea_SkyrendSlumgum_01','Gabezu',-5)
,('T_IngCrea_MeatHoney_01','Gabezu',-5)
,('T_IngCrea_KwoomEgg_01','Gabezu',-5)
,('ingred_green_lichen_01','Gabezu',-5)
,('T_IngFlor_LichenOrange_01','Gabezu',-5)
,('T_IngFlor_LichenBlue_01','Gabezu',-5)
,('T_IngCrea_Silk_01','Ganus Omathan',-5)
,('T_IngFood_EggOrnada_01','Garis Llanith',-2)
,('T_IngFood_FishSlaughterDried_01','Garis Llanith',-2)
,('food_kwama_egg_01','Garis Llanith',-2)
,('food_kwama_egg_02','Garis Llanith',-2)
,('ingred_kwama_cuttle_01','Garis Llanith',-1)
,('T_IngFood_FishSlaughterDried_01','Gelds Daral',-3)
,('T_IngFood_FishSlaughterDried_02','Gelds Daral',-3)
,('T_IngFood_CheeseColovian_01','Grelgi',-3)
,('T_IngFood_Olives_01','Grelgi',-3)
,('T_IngFood_MeatGuar_01','Harold Elk-Cleave',-3)
,('T_IngFood_MeatKagouti_01','Harold Elk-Cleave',-2)
,('T_IngFood_MeatKwama_01','Harold Elk-Cleave',-5)
,('T_IngFood_MeatVenison_01','Harold Elk-Cleave',-5)
,('ingred_hound_meat_01','Harold Elk-Cleave',-5)
,('T_IngFlor_Hamumroot_01','Hervil Aren',-10)
,('T_IngFood_MeatGuar_01','Hervil Aren',-6)
,('ingred_ash_yam_01','Hervil Aren',10)
,('ingred_guar_hide_01','Hervil Aren',-6)
,('T_IngCrea_ArmunHide_01','Hlava Daveleth',2)
,('T_IngCrea_KwamaChitin_01','Hlava Daveleth',-4)
,('ingred_alit_hide_01','Hlava Daveleth',-4)
,('ingred_guar_hide_01','Hlava Daveleth',-4)
,('ingred_kagouti_hide_01','Hlava Daveleth',-4)
,('ingred_netch_leather_01','Hlava Daveleth',-4)
,('ingred_bonemeal_01','Hulbert Vautri',1)
,('ingred_moon_sugar_01','Hulbert Vautri',-5)
,('food_kwama_egg_01','Indrasa Velador',-5)
,('ingred_bread_01','Indrasa Velador',-5)
,('ingred_saltrice_01','Indrasa Velador',-5)
,('ingred_scuttle_01','Indrasa Velador',-5)
,('T_IngCrea_HopperAntler_01','Irusa Sanys',-2)
,('T_IngCrea_KwoomFronds','Irusa Sanys',-3)
,('T_IngFlor_OrangeMoss_01','Issa Favelnim',5)
,('T_IngFlor_Hamumroot_01','Ivela Drals',-10)
,('T_IngFlor_Weepveil_01','Ivela Drals',-2)
,('ingred_corkbulb_root_01','Ivela Drals',10)
,('T_IngMine_Amber_01','Jorna Amber-Throat',4)
,('T_IngMine_OreGold_01','Jorna Amber-Throat',1)
,('ingred_diamond_01','Jorna Amber-Throat',2)
,('Ingred_sweetpulp_01','Kanitipilesha',-4)
,('T_IngCrea_HopperAntler_01','Kanitipilesha',-2)
,('T_IngCrea_KwoomEgg_01','Kanitipilesha',-2)
,('T_IngCrea_ShellParastylus_01','Kanitipilesha',-2)
,('T_IngCrea_SkyrenderVenom_01','Kanitipilesha',1)
,('T_IngFlor_PyrousUracia','Kanitipilesha',-5)
,('T_IngFlor_YamOrb_01','Kanitipilesha',-5)
,('ingred_red_lichen_01','Kanitipilesha',-5)
,('T_IngFood_CheeseColovian_01','Khazor gro-Bash',8)
,('T_IngFood_FishSlaughterDried_01','Khazor gro-Bash',4)
,('T_IngFood_FishSlaughterDried_02','Khazor gro-Bash',1)
,('ingred_bread_01','Khazor gro-Bash',3)
,('ingred_crab_meat_01','Khazor gro-Bash',-2)
,('T_IngFlor_Tanna_01','Kirste',-2)
,('ingred_hackle-lo_leaf_01','Kirste',-2)
,('T_IngFlor_Tanna_01','Kovan Ralethran',3)
,('ingred_hackle-lo_leaf_01','Kovan Ralethran',-30)
,('ingred_pearl_01','Lances-Under-Lantern',1)
,('T_IngFood_FishSlaughterDried_01','Leran Sethelas',-3)
,('T_IngFood_FishSlaughterDried_02','Leran Sethelas',-3)
,('ingred_scales_01','Leran Sethelas',-2)
,('T_IngDye_ImperialPurple_01','Linriah',2)
,('T_IngDye_Ultramarine_01','Linriah',-1)
,('T_IngDye_Verdigris_01','Linriah',-1)
,('T_IngDye_Vermilion_01','Linriah',-1)
,('T_IngFood_Cake_01','Lladres Sadreno',1)
,('T_IngFood_EggMolecrab_01','Lladres Sadreno',-5)
,('T_IngFood_EggOrnada_01','Lladres Sadreno',-5)
,('T_IngFood_Gorapple_01','Lladres Sadreno',-2)
,('T_IngFood_MeatCliffracer_01','Lladres Sadreno',-3)
,('T_IngFood_Pomegranate_01','Lladres Sadreno',-2)
,('T_IngSpice_OliveOil_01','Lladres Sadreno',-2)
,('food_kwama_egg_01','Lladres Sadreno',1)
,('ingred_bread_01','Lladres Sadreno',-3)
,('ingred_comberry_01','Lladres Sadreno',-5)
,('T_IngFood_FishSlaughterDried_01','Lorin Elval',-3)
,('food_kwama_egg_01','Lorin Elval',-2)
,('food_kwama_egg_02','Lorin Elval',-1)
,('ingred_bread_01','Lorin Elval',-2)
,('ingred_crab_meat_01','Lorin Elval',-3)
,('ingred_hound_meat_01','Lorin Elval',-1)
,('T_IngCrea_KwoomEgg_01','Madryn Nerathal',-3)
,('ingred_saltrice_01','Madryn Nerathal',-5)
,('ingred_scrib_jerky_01','Madryn Nerathal',-5)
,('ingred_scuttle_01','Madryn Nerathal',-5)
,('ingred_hackle-lo_leaf_01','Maldus Sendrul',2)
,('T_IngFood_CheeseColovian_01','Marcius Geta',2)
,('food_kwama_egg_01','Marcius Geta',1)
,('food_kwama_egg_02','Marcius Geta',1)
,('T_IngCrea_Eyestar_01','Maria Afrana',1)
,('T_IngCrea_KoboldTongue_01','Maria Afrana',1)
,('T_IngDye_Vermilion_01','Maria Afrana',-2)
,('T_IngFlor_DrumpearSeeds_01','Maria Afrana',2)
,('T_IngFlor_Fireflower_01','Maria Afrana',-2)
,('T_IngFlor_OrangeMoss_01','Maria Afrana',1)
,('T_IngFlor_SheggoShelf_01','Maria Afrana',1)
,('T_IngFlor_SujPod_01','Maria Afrana',1)
,('T_IngFlor_Tanna_01','Maria Afrana',5)
,('T_IngFlor_ThirrineLily_01','Maria Afrana',-4)
,('T_IngFood_Cookie_01','Maria Afrana',1)
,('T_IngMine_Amber_01','Maria Afrana',1)
,('T_IngMine_Bloodstone_01','Maria Afrana',1)
,('T_IngMine_Charcoal_01','Maria Afrana',5)
,('T_IngMine_Jade_01','Maria Afrana',1)
,('T_IngMine_OreGold_01','Maria Afrana',1)
,('T_IngMine_Rockcrystal_01','Maria Afrana',3)
,('ingred_bc_bungler''s_bane','Maria Afrana',3)
,('ingred_bc_coda_flower','Maria Afrana',2)
,('ingred_black_anther_01','Maria Afrana',1)
,('ingred_bloat_01','Maria Afrana',4)
,('ingred_dreugh_wax_01','Maria Afrana',1)
,('ingred_emerald_01','Maria Afrana',2)
,('ingred_heather_01','Maria Afrana',-3)
,('ingred_resin_01','Maria Afrana',5)
,('T_IngMine_Coal_01','Maynas Thilarvel',-2)
,('T_IngCrea_Eyestar_01','Meer-Ei',-2)
,('T_IngCrea_Newtscales_01','Meer-Ei',-2)
,('T_IngCrea_SturgeonMeat_01','Meer-Ei',-2)
,('T_IngCrea_SturgeonRoe_01','Meer-Ei',-4)
,('T_IngFlor_RedCoral_01','Meer-Ei',-2)
,('T_IngFlor_SeaCup_01','Meer-Ei',-5)
,('T_IngFlor_ThirrineLily_01','Meer-Ei',-3)
,('T_IngFood_FishSlaughterDried_01','Meer-Ei',-8)
,('T_IngFood_FishSlaughterDried_02','Meer-Ei',-4)
,('T_IngFood_FishSlaughterDried_03','Meer-Ei',-4)
,('T_IngFood_RiverstriderEgg_01','Meer-Ei',-3)
,('T_IngMine_PearlPink_01','Meer-Ei',-1)
,('ingred_dreugh_wax_01','Meer-Ei',-3)
,('ingred_pearl_01','Meer-Ei',-2)
,('ingred_scales_01','Meer-Ei',-7)
,('T_IngFood_EggOrnada_01','Muck-Raker',1)
,('T_IngFood_FishSlaughterDried_01','Muck-Raker',6)
,('T_IngFood_FishSlaughterDried_02','Muck-Raker',2)
,('T_IngFood_MeatCliffracer_01','Muck-Raker',2)
,('T_IngFood_MeatGuar_01','Muck-Raker',3)
,('T_IngFood_MeatKwama_01','Muck-Raker',3)
,('T_IngFood_MeatOrnada_01','Muck-Raker',2)
,('food_kwama_egg_01','Muck-Raker',6)
,('food_kwama_egg_02','Muck-Raker',14)
,('ingred_crab_meat_01','Muck-Raker',5)
,('ingred_hackle-lo_leaf_01','Muck-Raker',2)
,('ingred_scuttle_01','Muck-Raker',2)
,('T_IngMine_OreGold_01','Myron Rothalen',1)
,('ingred_emerald_01','Myron Rothalen',1)
,('T_IngCrea_SturgeonMeat_01','Naldyn Thavas',2)
,('T_IngFlor_ThirrineLily_01','Naldyn Thavas',2)
,('T_IngFood_FishSlaughterDried_01','Naldyn Thavas',3)
,('ingred_corkbulb_root_01','Naldyn Thavas',10)
,('ingred_crab_meat_01','Naldyn Thavas',2)
,('ingred_scales_01','Naldyn Thavas',3)
,('food_kwama_egg_02','Nalman Relarys',1)
,('ingred_hound_meat_01','Nalman Relarys',1)
,('T_IngFlor_DrumpearSeeds_01','Nurise Uvalyn',-2)
,('T_IngFlor_Hamumroot_01','Nurise Uvalyn',-2)
,('T_IngFlor_Tanna_01','Nurise Uvalyn',-3)
,('T_IngFlor_TempleDome_01','Nurise Uvalyn',-4)
,('ingred_bread_01','Nurise Uvalyn',-2)
,('T_IngFlor_AloeVeraPulp_01','Ovrosa Valen',2)
,('ingred_chokeweed_01','Ovrosa Valen',4)
,('ingred_corkbulb_root_01','Ovrosa Valen',1)
,('ingred_emerald_01','Ovrosa Valen',1)
,('ingred_marshmerrow_01','Ovrosa Valen',4)
,('ingred_resin_01','Ovrosa Valen',3)
,('ingred_shalk_resin_01','Ovrosa Valen',1)
,('ingred_wickwheat_01','Ovrosa Valen',6)
,('T_IngFlor_OrangeMoss_01','Palosenya',3)
,('T_IngFlor_RockburstClaw_01','Palosenya',-3)
,('T_IngFlor_SheggoShelf_01','Palosenya',-2)
,('T_IngFlor_SpongeLotusSeed_01','Palosenya',5)
,('T_IngFlor_Tanna_01','Palosenya',2)
,('food_kwama_egg_02','Palosenya',2)
,('ingred_hackle-lo_leaf_01','Palosenya',3)
,('ingred_scales_01','Palosenya',3)
,('Ingred_horn_lily_bulb_01','Pylameda',-2)
,('T_IngFlor_AloeVeraPulp_01','Pylameda',-5)
,('T_IngFlor_BlackrosePetal_01','Pylameda',-5)
,('T_IngFlor_BlisterSpore_01','Pylameda',-3)
,('T_IngFlor_BlueKanet_01','Pylameda',-5)
,('T_IngFlor_Weepveil_01','Pylameda',-5)
,('T_IngCrea _GremlinEarWax_01','Ra''Sato',1)
,('food_kwama_egg_01','Ralmyn Verith',-6)
,('food_kwama_egg_02','Ralmyn Verith',-6)
,('ingred_scrib_jerky_01','Ralmyn Verith',6)
,('T_IngFood_FishSlaughterDried_01','Ralsa Hardil',5)
,('T_IngFood_MeatGuar_01','Ralsa Hardil',2)
,('food_kwama_egg_01','Ralsa Hardil',1)
,('ingred_bread_01','Ralsa Hardil',1)
,('ingred_crab_meat_01','Ralsa Hardil',1)
,('ingred_hound_meat_01','Ralsa Hardil',1)
,('ingred_scrib_jelly_01','Ralsa Hardil',1)
,('ingred_scuttle_01','Ralsa Hardil',1)
,('T_IngCrea_HopperAntler_01','Ramora Atheron',-5)
,('T_IngFood_MeatCliffracer_01','Ramora Atheron',2)
,('ingred_racer_plumes_01','Ramora Atheron',-1)
,('T_IngFood_MeatAlit_01','Rogeed',-5)
,('T_IngFood_MeatCliffracer_01','Rogeed',-5)
,('T_IngFood_MeatKagouti_01','Rogeed',-5)
,('ingred_alit_hide_01','Rogeed',-5)
,('ingred_guar_hide_01','Rogeed',-5)
,('ingred_kagouti_hide_01','Rogeed',-5)
,('T_IngFlor_Tanna_01','Rovone Gathram',-5)
,('T_IngFood_MeatGuar_01','Rovone Gathram',-5)
,('ingred_guar_hide_01','Rovone Gathram',-5)
,('Ingred_lloramor_spines_01','Rugalmil',-5)
,('T_IngCrea_SkyrenderVenom_01','Rugalmil',1)
,('T_IngFlor_BlueKanet_01','Rugalmil',-5)
,('T_IngFlor_Cupling_01','Rugalmil',-5)
,('T_IngFlor_Tanna_01','Rugalmil',-5)
,('T_IngFlor_YamOrb_01','Rugalmil',-5)
,('T_IngFlor_Siyat_01','Ruram Salothran',-2)
,('T_IngFood_Siyat_02','Ruram Salothran',-1)
,('T_IngDye_Vermilion_01','Ruvene Falvanys',1)
,('T_IngFood_Cookie_02','Ruvene Falvanys',2)
,('T_IngFood_MeatHorse_01','Ruvene Falvanys',1)
,('ingred_bread_01','Ruvene Falvanys',3)
,('ingred_hound_meat_01','Ruvene Falvanys',-4)
,('ingred_hackle-lo_leaf_01','Dro''Dar',-4)
,('Ingred_scrib_cabbage_01','Sabia Bechand',-4)
,('T_IngFlor_Tanna_01','Sabia Bechand',-4)
,('T_IngFood_MeatGuar_01','Sabia Bechand',-4)
,('T_IngFood_MeatKagouti_01','Sabia Bechand',-4)
,('T_IngFood_MeatKwama_01','Sabia Bechand',-5)
,('food_kwama_egg_01','Sabia Bechand',-5)
,('ingred_ash_yam_01','Sabia Bechand',-10)
,('ingred_crab_meat_01','Sabia Bechand',-4)
,('ingred_saltrice_01','Sabia Bechand',-5)
,('T_IngFood_Fig_Dried_01','Saenus Dibuntus',-1)
,('Ingred_scrib_cabbage_01','Sanvyr Deroth',3)
,('T_IngFlor_Hamumroot_01','Sanvyr Deroth',4)
,('food_kwama_egg_01','Sanvyr Deroth',3)
,('food_kwama_egg_02','Sanvyr Deroth',3)
,('ingred_crab_meat_01','Sanvyr Deroth',6)
,('ingred_hackle-lo_leaf_01','Sanvyr Deroth',5)
,('ingred_hound_meat_01','Sanvyr Deroth',5)
,('ingred_bread_01','Saryth Kalmeran',2)
,('ingred_netch_leather_01','Satheri Vilas',-5)
,('T_IngCrea_BeetleShell_01','Senas Durel',-2)
,('T_IngCrea_BeetleShell_02','Senas Durel',-2)
,('T_IngCrea_ShellMolecrab_01','Senas Durel',-2)
,('T_IngCrea_ShellMolecrab_02','Senas Durel',-2)
,('T_IngFood_MeatKwama_01','Serila Othren',-3)
,('T_IngCrea_HopperMeat','Shairan',-4)
,('T_IngCrea_KwoomEgg_01','Shairan',-5)
,('T_IngCrea_KwoomFronds','Shairan',-2)
,('T_IngFlor_DrumpearSeeds_01','Shairan',-7)
,('T_IngSpice_Drumpear_01','Shairan',-2)
,('ingred_scrib_jerky_01','Shairan',3)
,('ingred_wickwheat_01','Shairan',4)
,('T_IngFlor_SaltCrocusPetal_01','Sirari Adras',-1)
,('T_IngFlor_SaltstrapLeaf_01','Sirari Adras',-1)
,('T_IngMine_Salt_01','Sirari Adras',-1)
,('Ingred_noble_sedge_01','Tarerume',1)
,('T_IngCrea_SkyrenderVenom_01','Tarerume',1)
,('T_IngFlor_LichenYellow_01','Tarerume',1)
,('T_IngFlor_SheggoShelf_01','Tarerume',2)
,('T_IngFlor_SmearSpores_01','Tarerume',1)
,('T_IngFlor_TempleDome_01','Tarerume',3)
,('T_IngFood_EggOrnada_01','Tarerume',2)
,('T_IngMine_Arsenic_01','Tarerume',-4)
,('ingred_scathecraw_01','Tarerume',3)
,('T_IngFlor_DrumpearSeeds_01','Taurwynn',-5)
,('T_IngSpice_Drumpear_01','Taurwynn',-5)
,('T_IngFood_Bread_01','Tenyara Sulereth',-5)
,('T_IngFood_Bread_02','Tenyara Sulereth',-5)
,('T_IngFood_Bread_03','Tenyara Sulereth',-5)
,('T_IngFood_Cookie_01','Tenyara Sulereth',-5)
,('T_IngFood_Cookie_02','Tenyara Sulereth',-5)
,('ingred_bread_01','Tenyara Sulereth',-5)
,('T_IngFood_EggOrnada_01','Terenu Aryon',-2)
,('T_IngFood_FishSlaughterDried_01','Terenu Aryon',-2)
,('T_IngFood_MeatGuar_01','Terenu Aryon',5)
,('ingred_crab_meat_01','Terenu Aryon',-3)
,('ingred_dreugh_wax_01','Terenu Aryon',1)
,('ingred_guar_hide_01','Terenu Aryon',2)
,('ingred_hound_meat_01','Terenu Aryon',2)
,('ingred_crab_meat_01','Tilse Marvayn',-4)
,('ingred_bread_01','Tirvel Bethrano',1)
,('ingred_scales_01','Tirvel Bethrano',1)
,('ingred_saltrice_01','Ularen Dereth',-2)
,('T_IngMine_OreSilver_01','Ulveni Salavel',-1)
,('ingred_bonemeal_01','Ulveni Salavel',-3)
,('T_IngFood_Bread_02','Undilo Llarys',-3)
,('T_IngFood_MeatKwama_01','Undilo Llarys',-2)
,('T_IngSpice_Drumpear_01','Undilo Llarys',1)
,('food_kwama_egg_01','Undilo Llarys',-6)
,('food_kwama_egg_02','Undilo Llarys',-3)
,('ingred_bread_01','Undilo Llarys',-2)
,('ingred_scuttle_01','Undilo Llarys',2)
,('T_IngCrea_YethResin_01','Ungodon',2)
,('T_IngFood_EggOrnada_01','Ungodon',2)
,('ingred_resin_01','Ungodon',5)
,('T_IngFood_FishSlaughterDried_01','Urnel Hareneth',-2)
,('T_IngFood_FishSlaughterDried_03','Urnel Hareneth',-3)
,('ingred_crab_meat_01','Urnel Hareneth',-3)
,('T_IngFood_MeatKwama_01','Vadrasa Indaram',-3)
,('food_kwama_egg_01','Vadrasa Indaram',-5)
,('food_kwama_egg_02','Vadrasa Indaram',-5)
,('ingred_kwama_cuttle_01','Vadrasa Indaram',-3)
,('T_IngCrea_VelkNectarSack_01','Valentin Lynier',3)
,('T_IngFood_WasabiRoot_01','Valentin Lynier',-1)
,('T_IngMine_Salt_01','Valentin Lynier',-4)
,('T_IngSpice_Anise_01','Valentin Lynier',3)
,('T_IngSpice_Cardamon_01','Valentin Lynier',3)
,('T_IngSpice_Curcuma_01','Valentin Lynier',3)
,('T_IngSpice_Drumpear_01','Valentin Lynier',-3)
,('T_IngSpice_Hibiscus_01','Valentin Lynier',3)
,('T_IngSpice_Muscat_01','Valentin Lynier',3)
,('T_IngSpice_Nigella_01','Valentin Lynier',3)
,('T_IngSpice_Pepper_01','Valentin Lynier',-1)
,('Ingred_scrib_cabbage_01','Valesu Adren',-3)
,('T_IngFlor_SpongeLotusSeed_01','Valesu Adren',-3)
,('T_IngFood_FishSlaughterDried_01','Valesu Adren',4)
,('T_IngFood_MeatGuar_01','Valesu Adren',-3)
,('T_IngFood_Sweetroll_01','Valesu Adren',1)
,('food_kwama_egg_01','Valesu Adren',-6)
,('food_kwama_egg_02','Valesu Adren',15)
,('ingred_bread_01','Valesu Adren',8)
,('ingred_hackle-lo_leaf_01','Valesu Adren',2)
,('ingred_hound_meat_01','Valesu Adren',6)
,('ingred_rat_meat_01','Valesu Adren',10)
,('food_kwama_egg_02','Vamona Folvyn',1)
,('ingred_bc_coda_flower','Vamona Folvyn',1)
,('ingred_bread_01','Vamona Folvyn',2)
,('ingred_crab_meat_01','Vamona Folvyn',5)
,('T_IngFood_MeatGuar_01','Varlyn Indaram',2)
,('T_IngFood_MeatKwama_01','Varlyn Indaram',1)
,('food_kwama_egg_01','Varlyn Indaram',2)
,('food_kwama_egg_02','Varlyn Indaram',6)
,('ingred_hackle-lo_leaf_01','Varlyn Indaram',4)
,('ingred_scuttle_01','Varlyn Indaram',3)
,('T_IngDye_ImperialPurple_01','Vilms Guralim',-4)
,('T_IngDye_Ultramarine_01','Vilms Guralim',-4)
,('T_IngDye_Verdigris_01','Vilms Guralim',-4)
,('T_IngDye_Vermilion_01','Vilms Guralim',-4)
,('T_IngDye_WhiteLead_01','Vilms Guralim',-4)
,('T_IngDye_YellowOchre_01','Vilms Guralim',-4)
,('ingred_moon_sugar_01','Vogier Hayne',12)
,('T_IngFlor_OrangeMoss_01','Vows-To-The-Soil',-2)
,('T_IngFood_MeatParastylus_01','Vows-To-The-Soil',-1)
,('ingred_chokeweed_01','Vows-To-The-Soil',-1)
,('ingred_muck_01','Vows-To-The-Soil',-2)
,('T_IngFood_FishSlaughterDried_01','Vulam Tellenith',5)
,('T_IngFood_FishSlaughterDried_02','Vulam Tellenith',-3)
,('T_IngFood_FishSlaughterDried_03','Vulam Tellenith',-3)
,('ingred_crab_meat_01','Vulam Tellenith',3)
,('T_IngCrea_SkyrendQStinger_01','Wilgod the Perennial',2)
,('T_IngCrea_SkyrenderVenom_01','Wilgod the Perennial',-2)
,('T_IngCrea_ThresherClaw_01','Wilgod the Perennial',2)
,('T_IngFlor_Siyat_01','Xastos Evorissia',-4)
,('T_IngCrea_HopperMeat','Yeshimmu',-6)
,('T_IngCrea_KwoomEgg_01','Yeshimmu',-4)
,('T_IngCrea_KwoomFronds','Yeshimmu',-3)
,('T_IngMine_Sapphire_01','Yeshimmu',-1)
,('ingred_kagouti_hide_01','Yeshimmu',1);
