INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Apprentice''s Alembic',0.5,'Alembic');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Apprentice''s Calcinator',0.5,'Calcinator');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Apprentice''s Mortar and Pestle',0.5,'Mortar and Pestle');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Apprentice''s Retort',0.5,'Retort');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Grandmaster''s Alembic',1.5,'Alembic');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Grandmaster''s Calcinator',1.5,'Calcinator');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Grandmaster''s Mortar and Pestle',1.5,'Mortar and Pestle');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Grandmaster''s Retort',1.5,'Retort');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Journeyman''s Alembic',1,'Alembic');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Journeyman''s Calcinator',1,'Calcinator');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Journeyman''s Mortar and Pestle',1,'Mortar and Pestle');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Journeyman''s Retort',1,'Retort');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Master''s Alembic',1.2,'Alembic');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Master''s Calcinator',1.2,'Calcinator');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Master''s Mortar and Pestle',1.2,'Mortar and Pestle');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('Master''s Retort',1.2,'Retort');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('SecretMaster''s Alembic',2,'Alembic');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('SecretMaster''s Calcinator',2,'Calcinator');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('SecretMaster''s Mortar and Pestle',2,'Mortar and Pestle');
INSERT INTO Tool(`Name`,`Quality`,`Type`) VALUES ('SecretMaster''s Retort',2,'Retort');
